### ISSUE TITLE
Currently only one sensor is generated with limited information content

### ISSUE THREAD

**Issue by CM000n** [DurgNomis-drol/ha_toyota#10]
**Describe the bug**
Hi, I just tested your Python library and your HA integration. I must say I am impressed with what you have done in such a short time! You even have an integration flow for the frontend already included. 

With that Integration flow I added my Toyota Corolla earlier. Adding works without any problems, unfortunately only one sensor with limited information content is generated afterwards:
![7686annt](https://user-images.githubusercontent.com/7945681/111125541-fe595c80-8571-11eb-8104-59e4a1ba31d3.JPG)

If I understand the code correctly, at least the ODO and the current tank level should already be provided, right? In the HA log, I see unfortunately no error messages

::Edit:: I was wrong. In fact there is the following error message in the HA log:
`2021-03-15 09:11:05 ERROR (MainThread) [custom_components.toyota.api] An unknown error occurred: 400, message='invalid character in header', url=URL('https://myt-agg.toyota-europe.com/cma/api/vehicle/MYCOROLLAVIN/addtionalInfo')
2021-03-15 09:16:07 ERROR (MainThread) [custom_components.toyota.api] An unknown error occurred: 400, message='invalid character in header', url=URL('https://myt-agg.toyota-europe.com/cma/api/vehicle/MYCOROLLAVIN/addtionalInfo')
`

**To Reproduce**

1. Go to 'Settings'
2. Go to 'Integrations'
3. Click on '+ Add Integration'
4. Add your MyT User Credentials
5. Only one sensor with limited information will be created

**Expected behavior**
Several sensors should be created, e.g. with current ODO and tank content.

**Comment by DurgNomis-drol** [comment]
@CM000n Thanks a lot. 😄 

I think it has something to do with how I encode the token in the header.

BTW If you enabled debug mode for the integration by putting this in your `configuration.yaml` you can see a lot more.

```yaml
logger:
  default: info
  logs:
     custom_components.toyota: debug
```

**Comment by DurgNomis-drol** [comment]
Also can you test if it works just using the python library. 😊

**Comment by CM000n** [comment]
Hi @DurgNomis-drol, thanks for your reply. 
I have, unfortunately I run into another problem there: https://github.com/DurgNomis-drol/mytoyota/issues/10

**Comment by CM000n** [comment]
Hi @DurgNomis-drol, what would be your recommended way to keep testing here?
Should I install the basic library again via `pip install mytoyota` in my HA Docker container now that you have published it on PyPi?
Also, with the version of the libary currently made available on PyPi, should the issue of missing sensors in HA already be fixed, or do you need to do something other for that?

**Comment by DurgNomis-drol** [comment]
There's is still a lot of work to do with the integration before i have something new for you to test. I will in the next couple of days(hopefully), push an update that you can test for me, but i still have somethings i need to sort out. 😁 I will ping you as soon as I have something that you can test 😊

**Comment by DurgNomis-drol** [comment]
@CM000n Are you ready to test it again? 🎉 

I have released the first version of `mytoyota` python module and I am now ready to test here again.

Please remove the integration and reinstall it. 😄

**Comment by CM000n** [comment]
Wohooo, that looks much better now 🎉
![4524352435342t](https://user-images.githubusercontent.com/7945681/111588459-e2e59000-87c3-11eb-8ef7-84e1231f1e28.JPG)


Strangely, however, it still does not generate a sensor for the odometer. The only thing that works is the current fuel level in %.
For the last park location and the battery it creates sensors, but they are not available.

Speaking of which, what should be displayed in the battery sensor? The original MyT app, at least in my case, does not provide any information about the charge level of the hybrid battery either.
However, the parking information works via the MyT app for me and also via the Python Libary from https://github.com/calmjm/tojota

**Comment by DurgNomis-drol** [comment]
Thanks for the feedback 😊

About the parking sensor, i think I am gonna change it to a device tracker instead, so it can be used natively on maps in HA. About address returning `None`, I can implement a library that translate latitude and longitude into a know address. What is your opinion about this? Will this be more useful?

Your right about the `odometer_unit` key should be `mileage_unit`. I just forgot to change it.

About battery and hvac. I don't know how much info is available, but I think it depends on the car model. For this i will need someone to get the information through `mytoyota` manually. But i still have some work there for it to work.

In general, what features do you think would be most useful for the user?

**Comment by CM000n** [comment]
Hi Simon, thanks for the feedback,

I find the use of a device tracker for the last parking position very useful. The geo-coordinates that currently I still get via Calmjm's Python Libary, I also use to display them as a device tracker in Home Assistant:
![676575647654t](https://user-images.githubusercontent.com/7945681/111592914-b03e9600-87c9-11eb-9d7d-a321c913275a.JPG)

In my case, I never cared about actual street or city names in HA. For me, it's usually enough to look at the map, or a rough division by HA zones, for which latitude and longitude are actually sufficient.
I think you should not invest too much work in it, as long as it is not directly provided by the Toyota API, or the conversion of geocode coordinates is natively supported by Homeassistant. If someone really needs it, they can currently use Custom Components for that as well, which focuses on that: https://community.home-assistant.io/t/google-geocode-custom-component-gps-to-street-address/22233

Of course, it would also be cool to have real-time location and route data, but that's not possible, since Toyota probably only ever transmits the information when the car is at a standstill after a driven route.
Unfortunately, this also means that the routes driven cannot be mapped so nicely in HA. I have looked in, but unfortunately all geo coordinates of a driven route are transmitted as a bulk event and the MyT app then simply interpolates between these points. But Home Assistant would probably need real/near-time data for this.

For me, the vehicle statistics are currently the most useful, which I can retrieve via Calmjm's library and thus store away in my database:
![6546456546t](https://user-images.githubusercontent.com/7945681/111593428-378c0980-87ca-11eb-903e-6d2edf028c85.JPG)
But presumably the implementation of these is currently a bit more complex and must be done gradually?

I think you are right about the battery sensor and additional features. Probably this will be a bit of trial an error as long as there is no official documentation from Toyota of their API and an overview of which vehicle supports which functions.
I think if HA Toyota starts with the last parking position, fuel level and odemeter, that would definitely be a good start 😊

**Comment by DurgNomis-drol** [comment]
@CM000n 

I just pushed an update and it should fix the problem with the wrong key name for `odometer_unit`. I have disabled the Battery sensor and the HVAC sensor for now until I can research it a bit more.

I have implement a device tracker that shows latest information, ala. the way you have in the screenshots.  (I can't test it, so i hope it works 🤞).  I actually didn't know about that custom_component, seems very useful. Thanks for linking it.

About realtime tracking. I don't think it is feasible as you also have found out.

About vehicle statistics, we will have to make a plan on how many sensors there should be and what they will present as state, and as attributes. We could also make it possible to enabled more statistical sensors through the options menu so we don't overload the end user at first. This is probably gonna take some trial until we find a good middel ground for everyone.

Vehicle statistics is probably one of the first things we should implement as I agree that it is very useful. How do you calculate for each month or year (perhaps weeks also?) ? Is it done through template sensors?

**Comment by CM000n** [comment]
I get the statistics for year, week, day, directly from calmjm's statistics.py script, which in turn probably gets them directly from the Toyota API? Look here: https://github.com/calmjm/tojota/blob/master/statistics.py

I just adjusted the calculation logic for me, so that I only get data from the current year, week, day etc. Calmjm has only subtracted 365 days for this. I have also once created a small PR for him, but he has probably not yet looked at: https://github.com/calmjm/tojota/pull/29/files

By the way, the sensor for tank level and odometer now work wonderfully. :-) But when setting up the odometer there is still a problem with the data format:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 319, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 104, in state
    zone_state = zone.async_active_zone(
  File "/usr/src/homeassistant/homeassistant/components/zone/__init__.py", line 113, in async_active_zone
    zone_dist = distance(
  File "/usr/src/homeassistant/homeassistant/util/location.py", line 74, in distance
    result = vincenty((lat1, lon1), (lat2, lon2))
  File "/usr/src/homeassistant/homeassistant/util/location.py", line 99, in vincenty
    U1 = math.atan((1 - FLATTENING) * math.tan(math.radians(point1[0])))
TypeError: must be real number, not str
```

Greetings

**Comment by DurgNomis-drol** [comment]
Great to here it works! 

The error should be fixed now, it was a missing conversion of longitude and latitude from string to float in the device_tracker. 😄

I missed that part of his script. I have started implementing it in `mytoyota` and when i get my car and can test it, i will start looking into implementing it here. 😄

**Comment by CM000n** [comment]
Mhmm, I just tested it. But I still get the same error message for the device_tracker

**Comment by DurgNomis-drol** [comment]
I forgot to push my fix yesterday 🤦 Thanks for fixing it.

**Comment by CM000n** [comment]
Hehe, I almost thought so. 😄
I think now that HA Toyota generates 3 sensors with useful information and even a device_tracker, we can close this issue, right?
Should I open a feature request for the implementation of the driving statistics, so that we at least have it recorded somewhere?

Thanks again for your efforts. This is really great work that you are doing here!

**Comment by DurgNomis-drol** [comment]
Yes lets close this. 

And that would be great if you would do that. If you have other features you would like to see, you are more the welcome to add them too. 😄 

Im already a very long way with implementing it in `mytoyota`. Just waiting for me to be able to test it. 

And thanks for the kind words. It is a huge motivator when spending time on this. 😄

**Comment by Joonaskaru** [comment]
Stumbled upon it and i am having an issue, maybe somebody can point me to correct direction.
I seem to struggle with getting more than couple of sensors to HA.
CAR: Corolla 2020.

I have now the location, odometer, and general data about the car. Like the first post.
To my understanding the Integration should generate more data. Any tips?

HA is running in a docker. 
I am not the best at coding but with some trial and error i can make some stuff running.

**Comment by DurgNomis-drol** [comment]
Is your car an EV? 

You should also have fuel information.

**Comment by Joonaskaru** [comment]
It is an hybrid, By previous posts it seems to be the same model of car, Corolla Hybrid 1.8L

2021-07-31 14:10:57 DEBUG (MainThread) [custom_components.toyota] [{'alias': 'Corolla HB/TS', 'vin': 'xxxxxxxxxxxxxxxx', 'details': {'brand': 'TOYOTA', 'deviceAddedOn': '2021-06-22T09:20:37.179Z', 'deviceId': 'xxxxxxxxxxxxxxxxx', 'deviceTypeName': 'HARMANMM19RETROTOY', 'engine': '1.8L (HEV special)', 'entitledBy': 'CUSTOMER', 'entitledOn': '2021-07-29T09:11:45.824Z', 'exteriorColour': '1J6 ', 'fuel': 'PETROL', 'generation': 'MM19RETRO', 'grade': 'High', 'horsePower': 98, 'hybrid': True, 'id': 2236013, 'imageUrl': 'https://dj3z27z47basa.cloudfront.net/b64f874c-0519-466f-a9bd-4007c3f8cc62', 'interiorColour': '20', 'isEntitled': True, 'isNC': False, 'licensePlate': '-UK09726040', 'modelCode': 'CR', 'modelDescription': 'Corolla HB/TS', 'modelDocumentId': '12345', 'modelName': 'Corolla HB/TS', 'navSubType': 'Low', 'navType': 'TOY', 'owner': False, 'ownerFlag': False, 'productionYear': '2019', 'source': 'NMSC', 'transmission': 'Continuously Variable Transmission', 'transmissionType': 'CVT', 'vehicleAddedOn': '2021-07-29T09:10:59.751Z'}, 'status': {'battery': None, 'hvac': None, 'odometer': {'mileage': 21752, 'mileage_unit': 'km'}, 'parking': {'event': {'lat': '59.40128472', 'lon': '24.79218611', 'timestamp': '1627722107000'}, 'tripStatus': '0'}}, 'servicesEnabled': {'connectedServices': True}}]

By the log output it seems that that is all i get from Toyota Services. Hoped for Fuel level also.

**Comment by CM000n** [comment]
The fuel level is definitely not available for all Corolla hybrid models. Also in the original MyT app. I am also active in a German Corolla forum. There we had it some time ago also about this topic. So exactly we could not identify from when the fuel level was introduced, but it seems as if this was gradually introduced with the model series from year of manufacture 2021, or late 2020. So therefore it is probably not a problem with the custom component ;-) Can you see the tank level then in the originslen Toyota app @Joonaskaru  ? If it is not available there, it will not be able to determine the custom component.

**Comment by DurgNomis-drol** [comment]
@CM000n Oh, thanks for clearing that up!

**Comment by Joonaskaru** [comment]
Hello! Thanks for clearing that up. 
I have an early 2019 model from 2020 Corolla Hybrid.  
Weird that they phase in these kinds of functionalities. 
MyT app also soes not have fuel level, held my hope that it may be buried somewhere...
Seems that I do not get all the fancy bells and whistles then.  Case closed
