### ISSUE TITLE
ValueError: entity_category must be a valid EntityCategory instance

### ISSUE THREAD

**Issue by felalex** [DurgNomis-drol/ha_toyota#106]
**Describe the bug**
I can see only a subset of data, which was available before:

Sensors:

- Current month statistics
- Current week statistics
- Current year statistics
- Fuel Tank
- Odometer
- Over all status

Diagnostics:

- Parking location

All others are not available and the log shows the following errors:

**To Reproduce**

Just stopped working after the update.

**Expected behavior**
Integration works.

**Additional context**
Here's the error I see in the log:
Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:383
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 3:45:29 PM (4 occurrences)
Last logged: 3:45:51 PM

Error adding entities for domain sensor with platform toyota
Error while setting up toyota platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_registry.py:383
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 3:45:29 PM (4 occurrences)
Last logged: 3:45:51 PM

Error adding entities for domain binary_sensor with platform toyota
Error while setting up toyota platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by DurgNomis-drol** [comment]
Just published a new release with the fix. (I had it fixed in the repo just forgot to make a release, sorry about that 😜)

**Comment by felalex** [comment]
Confirmed. Thank you very much.
