### ISSUE TITLE
HA 2022.6 brakes Toyota 

### ISSUE THREAD

**Issue by homonto** [DurgNomis-drol/ha_toyota#108]
**Describe the bug**
Setup failed for custom integration toyota: Requirements for toyota not found: ['mytoyota==0.7.7'].

**To Reproduce**
Upgrade HA to 2022.6

**Comment by homonto** [comment]
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 20:41:07 (9 occurrences)
Last logged: 20:43:18

Unable to install package mytoyota==0.7.7: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb635deb0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb5a331c0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb5a33400>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb5a335e0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb5a33790>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb5a33940>: Failed to establish a new connection: [Errno -2] Name does not resolve')) WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Unable to install package mytoyota==0.7.7: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f92458640>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f920462e0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f92046520>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f92046700>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f920468b0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/5d/33/1be94b3e56576736dddc7cfc4cbc5faf5511e689c70c18eae119b199be8e/mytoyota-0.7.7-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f92046a60>: Failed to establish a new connection: [Errno -2] Name does not resolve')) WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Unable to install package prettytable==3.0.0: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1746850>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1746d00>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1746f40>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb161a040>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb161a2e0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb161a490>: Failed to establish a new connection: [Errno -2] Name does not resolve')) WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Unable to install package prettytable==3.0.0: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fae73ea60>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fae73ed60>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fae73efa0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fae111190>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fae111340>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fae1114f0>: Failed to establish a new connection: [Errno -2] Name does not resolve')) WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Unable to install package prettytable==3.0.0: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb22705b0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1e5d280>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1e5d4c0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1e5d6a0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1e5d850>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/71/4f/82c03ec59c6b9b1caaa60e1e7d7713f4587a75824207e41698effc8ca5b7/prettytable-3.0.0-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb1e5da00>: Failed to establish a new connection: [Errno -2] Name does not resolve')) WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by DurgNomis-drol** [comment]
It seems to be a DNS problem connecting to Toyota's servers, not much i can do about it.

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
