### ISSUE TITLE
Data availability is unstable

### ISSUE THREAD

**Issue by Urmus-dev** [DurgNomis-drol/ha_toyota#112]
**Describe the bug**
I'm pretty sure the issue is not from this side, but I don't know where to look for help
In nearly half the day, the service is reported unavailable and asking for configuration verification.
Before using the integration, I never noticed unavailable data in MyT application, but I guess I paid not the same attention as my HA dashboard. Now, service is often unavailable, even in the app/the website, even if they say my vehicule is connected.

Here is what I find in the logs:

> 2022-06-21 21:19:53 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: can only concatenate str (not "dict") to str
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
>     return await self.update_method()
>   File "/config/custom_components/toyota/__init__.py", line 105, in async_update_data
>     data = await asyncio.gather(
>   File "/usr/local/lib/python3.9/site-packages/mytoyota/client.py", line 419, in get_driving_statistics
>     raw_statistics = await self.api.get_driving_statistics_endpoint(
>   File "/usr/local/lib/python3.9/site-packages/mytoyota/api.py", line 96, in get_driving_statistics_endpoint
>     return await self.controller.request(
>   File "/usr/local/lib/python3.9/site-packages/mytoyota/controller.py", line 219, in request
>     "Internal server error occurred! - " + response
> TypeError: can only concatenate str (not "dict") to str
> 2022-06-21 21:19:53 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 6.332 seconds (success: False)

And these:

> 2022-06-21 21:26:09 ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: Update canceled! Toyota's API was too slow to respond. Will try again later...
> 2022-06-21 21:26:09 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 16.145 seconds (success: False)

**To Reproduce**
I followed the instructions on the readme.
My setup is a Docker image on a Ubuntu server 22.04 VM on a Qnap server.

**Expected behavior**
Well, more data, I guess?

**Screenshots**
![image](https://user-images.githubusercontent.com/69540453/174898077-b1eaa488-a6cb-4f21-88a2-a219f54beab5.png)
![image](https://user-images.githubusercontent.com/69540453/174898137-acfee683-029a-492a-bbd4-89c3358b8a75.png)

**Additional context**
Europe, France.
I check data in the MyT app and https://www.toyota.fr/apps/customerportal#/

**Comment by DurgNomis-drol** [comment]
Their servers are very unstable, this problem you have, I have seen this a lot when developing this integration. For some reason the API returns errors in situations where it shouldn't. I have no answer on how to fix it for now unfortunately.

**Comment by primeroz** [comment]
just started using this integration and is great when toyota api works :) 

can this issue be related in any way to https://github.com/DurgNomis-drol/ha_toyota/pull/95 ?

**Comment by DurgNomis-drol** [comment]
No unfortunately not, Toyota's API is not meant for constant polling, and it errors out because of this.

**Comment by primeroz** [comment]
sorry for polluting the issue. my issue was with timeouts. I increased in my local copy both the interval and the timeout and things look good for now. thanks again for the amazing integration

**Comment by DurgNomis-drol** [comment]
What did you increase it to?

**Comment by primeroz** [comment]
update every 600s ( i don't really need it more precise than that for my needs ) and async timeout to 60s

**Comment by rpetteruti** [comment]
Hello, this integration is great but the API are very unstable, would be great to not ‘push’ the unaivalable status in order to just keep the last value. Do you think is possible and does it make sense? Thank you!

**Comment by 0xF16** [comment]
I'm also experiencing it, even with the updated interval (I use the version [7afd17d](https://github.com/DurgNomis-drol/ha_toyota/commit/7afd17df5abc9c37bc279f346cfdc694550209ee)). Wondering if we cannot just cache the last results and show old status/data instead of "Unavailable"?

**Comment by beralios** [comment]
Strange behaviour here.. I have instability or "no data" only for Weekly statistics (sensor.c_hr_current_week_statistics)..
But I have month & year.. and also I have them on MyT app..
What could be the problem ?

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
