### ISSUE TITLE
Statistics sensors data erased when having more than one car

### ISSUE THREAD

**Issue by Fredzxda** [DurgNomis-drol/ha_toyota#117]
When more than one car is associated to the same MyT account, statistics data are erase with the last one during data parsing.
![Error](https://user-images.githubusercontent.com/37531742/199275932-af4e1d7b-12e3-4d4b-ad43-b69c684199b2.png)

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
