### ISSUE TITLE
Receiving HTTP 429 errors

### ISSUE THREAD

**Issue by ajain-93** [DurgNomis-drol/ha_toyota#122]
**Describe the bug**
Unable to update any of the sensors, all sensors showing up as unavailable.
Started receiveing HTTP 429 errors since 12 hours ago.

**To Reproduce**
\-

**Expected behavior**
The sensors updates at interval.

**Screenshots**
![image](https://user-images.githubusercontent.com/26898985/204639443-8eb0e03a-66d1-4ac7-8fab-e839dd74bcec.png)

![image](https://user-images.githubusercontent.com/26898985/204639304-5cf84476-9a52-4e18-b9ff-6d8cd35d7bea.png)

**Additional context**
Log ouput:
```
This error originated from a custom integration.

Logger: custom_components.toyota
Source: helpers/update_coordinator.py:223
Integration: Toyota Connected Services (documentation, issues)
First occurred: 9:13:20 PM (5 occurrences)
Last logged: 9:15:07 PM

Error fetching toyota data: HTTP: 429 - Too Many Requests. Please try again later.
```

**Comment by Patronen** [comment]
Same issue with my system. I've tried deleting both the integration and the HACS package while restarting HA with no effect. Following this issue, thanks for reporting

**Comment by Aad3229** [comment]
Exactly the same here. All sensors unavailable:
Error fetching toyota data: HTTP: 429 - Too Many Requests. Please try again later.
Error fetching toyota data: Update canceled! Toyota's API was too slow to respond. Will try again later...

**Comment by ajain-93** [comment]
Tried updating the integration using the github-repo (rather than the release in HACS).

After `Disabling` and `Enabling` the integration, there is an `Failed to set up` error on the integration screen.
![image](https://user-images.githubusercontent.com/26898985/204781784-aa5230a6-43fe-49c7-bf95-8f6df6074a4a.png)

Checking the logs, it shows the same 429, as well as an `Update Cancelled` error.

**Log Output**
```
This error originated from a custom integration.

Logger: custom_components.toyota
Source: helpers/update_coordinator.py:223
Integration: Toyota Connected Services (documentation, issues)
First occurred: 8:52:54 AM (139 occurrences)
Last logged: 11:58:46 AM

Error fetching toyota data: HTTP: 429 - Too Many Requests. Please try again later.
Error fetching toyota data: Update canceled! Toyota's API was too slow to respond. Will try again later...
```

**Comment by lkucytowski** [comment]
It's now taking forever to pull any data in the Toyota app, somebody in Toyota needs to restart the NGINX ;)
Their infrastructure is in shambles, probably running on a potato, hopefully the problem will go away soon.

**Comment by DurgNomis-drol** [comment]
> It's now taking forever to pull any data in their official app, somebody in Toyota needs to restart the NGINX ;) Their infrastructure is in shambles, probably running on a potato, hopefully the problem will go away soon.

Toyota's servers are the worst things I have ever worked with 😆 😭  They crap out for no reason what so ever

**Comment by fransward** [comment]
Same here. Could it be that they modified their api rate limiter?

**Comment by ald3baranfr** [comment]
hello
same issue for me.

**Comment by daha76** [comment]
Same issue for me. I can't get it work for several days...

**Comment by rpetteruti** [comment]
Same here

**Comment by ndriu** [comment]
same here for many hours...

**Comment by AdrianStanciu22** [comment]
A possible explanation could be here: https://twitter.com/samwcyo/status/1597792097175674880

**Comment by ajain-93** [comment]
The API for Toyota (MyT) is still online. Debuggning a HASS integration was a little bit too much for me. I tried my shot reverse-engineering the API and realised that this integration is an [spinoff/inspired](https://community.home-assistant.io/t/toyota-connect/205485/36) from the project https://github.com/calmjm/tojota.

I have now [created a fork](https://github.com/ajain-93/tojota) of the above project, which publishes data to MQTT when executed (this can be accomplished via an automation and [Shell Command](https://www.home-assistant.io/integrations/shell_command/)), from which HASS can automatically pick up the data. Note, I do not have any remote control functions, hence they are not present in the published MQTT data.

If @DurgNomis-drol could point me in the right direction for debug I can help try to solve this issue in this integration.

**Comment by primeroz** [comment]
even with testing just the simple example in https://github.com/DurgNomis-drol/mytoyota/tree/v0.7.7 i get 429 as soon as `client.get_vehicle_status(car)` is called which seems to issue 4 concurrent requests https://github.com/DurgNomis-drol/mytoyota/blob/v0.7.7/mytoyota/client.py#L248 

I guess we need to limit the number of concurrent requests ?

**Comment by Iture** [comment]
No, it doesn't work (I've tried this approach)
I just added an issue here: 
https://github.com/DurgNomis-drol/mytoyota/issues/204

**Comment by DurgNomis-drol** [comment]
@Iture  issue seems like a good reason as to why it does not work, or they have added aggressive rate limiting to their API to stop integrations like this from getting data from them. Either way, this will require substantial work to fix, if even possible.

**Comment by lucianlazar1983** [comment]
i debugged network connections while the app was open and found http calls to this endpoints:myt-agg.toyota-europe.com ( i think this is it, had a lot of them while calling for trips)events.mapbox.comapi.mapbox.comI am trying to find a way to get the payload too but it will be difficult as i have an iphone.—Lazar LucianOn 6 Dec 2022, at 21:24, Simon Hansen ***@***.***> wrote:﻿
@Iture  issue seems like a good reason as to why it does not work, or they have added aggressive rate limiting to their API to stop integrations like this from getting data from them. Either way, this will require substantial work to fix, if even possible.

**Comment by ajain-93** [comment]
> @joro75:
> The server endpoint seems to be oke. The mytoyota library that is being used is also connecting to: "https://myt-agg.toyota-europe.com/". Can you check or determine if the complete URL of the endpoint is still: "https://myt-agg.toyota-europe.com/cma/api" (including the 'cma/api' suffix?)

There are essentially three different endpoints used:
* https://ssoms.toyota-europe.com/authenticate
  * Authentication
* https://cpb2cs.toyota-europe.com/api/
  * List of Vehicles
  * Vehicle Metadata
  * Workshop History
  * Location Status
  * Trips
  * Statistics (Trip Summaries)
* https://myt-agg.toyota-europe.com/cma/api/
  * Odometer/Fuel
  * Remote control

**Comment by DurgNomis-drol** [comment]
See #204 for the reason it does not work, will publish a fixed version soon

**Comment by DurgNomis-drol** [comment]
Can confirm fix works, will be releasing a new version shortly!

**Comment by primeroz** [comment]
thank you

**Comment by joro75** [comment]
@ajain-93 : Thanks for the information. Most of the endpoint URL's are also being used by mytoyota. However (to my suprise), some of them are also slightly different. That's interesting, but no need to change it at this moment.

**Comment by ajain-93** [comment]
@joro75:
https://ssoms.toyota-europe.com/authenticate and https://cpb2cs.toyota-europe.com/api/ones i mentioned above are the ones I was able to reverse-engineer by checking out the [Swedish MyT](https://www.toyota.se/apps/customerportal#/) portal on the web. The last one though, doesn't show up for me in my webbrowser.
