### ISSUE TITLE
Can't update credentials in integration

### ISSUE THREAD

**Issue by gstevenson** [DurgNomis-drol/ha_toyota#124]
**Describe the bug**
If you change your Toyota credentials, the integration errors with 

`Failed to set up: Login failed, check your credentials! 401 - {"httpErrorCode":401,"message":"Couldn't authenticate with given username/password"}`

.. but doesn't provide a way to supply the updated ones.

**To Reproduce**
1. Update MyT password
2. Refresh integration
3. Error will be display

**Expected behavior**
Probably fine to display an error, but the UI should allow you to update the stored credentials

**Comment by DurgNomis-drol** [comment]
If you choose to setup the integration again without deleting it, it will just overwrite the old integration with the new login info
