### ISSUE TITLE
vehicle without vin

### ISSUE THREAD

**Issue by pbe-axelor** [DurgNomis-drol/ha_toyota#133]
`client.get_vehicles()` can return vehicles that don't have any `vin`

This is associated to a multimedia system Touch & Go. Here is an example of the data : 
```
{
    'vin': '',
    'brand': 'TOYOTA',
    'deviceId': '[REDACTED]',
    'generation': '[REDACTED]'',
    'deviceTypeName': '[REDACTED]'',
    'navType': 'TOY',
    'navSubType': 'Low',
    'source': 'NMSC'
  }
```

This cause `404 Not Found` issues when trying to fetch the vehicle status from `client.get_vehicle_status(car)` and integration fail to setup.

```
ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: HTTP: 400 - {"timestamp":1677989012440,"status":400,"error":"Bad Request","message":"INVALID VIN FORMAT","errorCode":"CMA400"}
ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: HTTP: 404 - <!DOCTYPE html>
 <html lang="en">
 <head>
 <meta charset="utf-8">
 <title>Error</title>
 </head>
 <body>
 <pre>Cannot GET /vehicle/user/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/vehicle/</pre>
 </body>
 </html>
```

**Comment by pbe-axelor** [comment]
Yes, there is no `vin` associated to the car returned by `client.get_vehicles()`.

Using that script, https://github.com/DurgNomis-drol/mytoyota#usage, here are the cars returned : 
```
[
  {
    'id': [REDACTED],
    'vin': '[REDACTED]',
    'isNC': False,
    'isOneAppMigrated': False,
    'alias': 'RAV4 PHEV',
    'owner': False,
    'vehicleAddedOn': '[REDACTED]',
    'isEntitled': True,
    'entitledBy': 'CUSTOMER',
    'entitledOn': '[REDACTED]',
    'ownerFlag': False,
    'source': 'NMSC',
    'horsePower': 185,
    'hybrid': True,
    'fuel': 'PETROL',
    'engine': '2.5 TNGA PHEV',
    'transmissionType': 'CVT',
    'transmission': 'Continuously Variable Transmission',
    'grade': 'Limited',
    'modelName': 'RAV4 PHEV',
    'modelCode': 'RE',
    'interiorColour': '20',
    'exteriorColour': '2QZ ',
    'imageUrl': '[REDACTED]',
    'deliveryCountry': 'FR',
    'productionDate': '2021-04-22',
    'modelDocumentId': '[REDACTED]',
    'productionYear': '2021',
    'licensePlate': '[REDACTED]',
    'modelDescription': 'RAV4 PHEV'
  },
  {
    'vin': '',
    'brand': 'TOYOTA',
    'deviceId': '[REDACTED]',
    'generation': 'MM17PLUS',
    'deviceTypeName': 'ToyotaTouch2 MM19',
    'navType': 'TOY',
    'navSubType': 'Low',
    'source': 'NMSC'
  }
]
``` 
The first entry is the RAV4 PHEV car, the second is the multimedia system associated to the car.

**Comment by DurgNomis-drol** [comment]
Right, it seems that Toyota have chosen to make a separat entry for their nav units. Right now this is not supported, and I don't have access to a car that does this. So I can't tell what needs to be done for this to work. Allowing vehicles without a vin number, will not add support for these navunits anyways. But we should add a check that just ignores cars with no vin number so the we don't get an error.

**Comment by pbe-axelor** [comment]
> Allowing vehicles without a vin number, will not add support for these navunits anyways.

Yes, agree with that.

> But we should add a check that just ignores cars with no vin number so the we don't get an error.

I solved the issue by adding a check while iterating over cars : 

```diff
             cars = await with_timeout(client.get_vehicles())
 
             for car in cars:
+                if not car['vin']:
+                    continue
+
                 vehicle = await client.get_vehicle_status(car)
```

I can submit a PR if you want.

**Comment by DurgNomis-drol** [comment]
Please do 😃 Contributions are always welcome
