### ISSUE TITLE
Error 400 "INVALID VIN FORMAT" & Error 404

### ISSUE THREAD

**Issue by marcolibe89** [DurgNomis-drol/ha_toyota#138]
Hi, i'm reporting in HA error HTTP 400 "INVALID VIN FORMAT" and error HTTP 400. 

Already tryied to totally remove ha_toyota with clean reinstall but i still have same issue. 

Here you can see my debug log captured from HomeAssistant
```text
2023-04-12 13:49:51.737 ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: HTTP: 400 - {"timestamp":1681300191694,"status":400,"error":"Bad Request","message":"INVALID VIN FORMAT","errorCode":"CMA400"}
2023-04-12 13:51:16.284 ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: HTTP: 404 - {
"servlet":"dispatcherServlet",
"message":"Not Found",
"url":"/api/vehicle/addtionalInfo",
"status":"404"
}
2023-04-12 13:52:40.885 ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: HTTP: 404 - {
"servlet":"dispatcherServlet",
"message":"Not Found",
"url":"/api/vehicles/remoteControl/status",
"status":"404"
}
2023-04-12 13:54:13.707 ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: HTTP: 404 - <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /vehicle/user/10xxxxx-5xxc-4xx5-8xx1-7xxxxxxxxcf/vehicle/</pre>
</body>
</html>
```

**Comment by DurgNomis-drol** [comment]
Are you using a headunit or a car?

**Comment by marcolibe89** [comment]
i have Europen version of RAV4 PHEV , my headunit is standard ToyotaTouch2 MM19

**Comment by DurgNomis-drol** [comment]
Have you connected the RAV4 or the Toyota Touch2 Headunit in the MyT app?

**Comment by marcolibe89** [comment]
yes, i use Android App MyT since the beginning, i manage charge info and other car information.

**Comment by marcolibe89** [comment]
Guys i have just found the problem: Logging directily via web browser on toyota website i have found pop-up message with "New headunit found, register it to a car".

Checking serial no. i have found this headunit was installed on my old C-HR car (maybe new owner tried something) 

To solve this issue you have to select "do not register this headunit" directly from website, and pop-up message disapear.
on MyT app this prompt do not appear, you will see it only on web.

Thanks for precious suggestion @DurgNomis-drol

**Comment by DurgNomis-drol** [comment]
If I remember correctly, the new user needs to contact Toyota to get his headunit disassociated with your account if he wants to use MyT
