### ISSUE TITLE
Rav4 PHEV plug in range

### ISSUE THREAD

**Issue by Toyziki** [DurgNomis-drol/ha_toyota#143]
Thank you for this integration. I report that the Toyota integration for the Rav4 PHEV has lost the Range (that is the battery range that reported in miles). The display shows unavailable and I confirm that in April it was working. I have not changed the configuration.

![Screenshot_20230520-074001](https://github.com/DurgNomis-drol/ha_toyota/assets/128059871/562d8e0c-8374-4e04-975e-034862356ea1)

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
