### ISSUE TITLE
missing entities and numberplate

### ISSUE THREAD

**Issue by trytogetme85** [DurgNomis-drol/ha_toyota#144]
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/20819567/47cbf23c-d76e-4f71-b8d1-e064c58a2ee8)

Some of the entities seems missing, and not provided anymore.
Happens for my corolla with the "location" and "current month statistics"

but my numberplate seems changing every hour:
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/20819567/5f16797a-16c0-4def-b6cd-b52c3332f826)

**Comment by AUSF** [comment]
It's a few months that I'm having the same behaviour. I have noticed that trying to reload the integration some times makes some sensors to re-appear. Very likely something has changed in the communication protocol and the integration is failing on timeouts or something similar... :-(

**Comment by Andream69** [comment]
Ho istallato il tutto come da procedura (Hacs) ma riesco a vedere solo il numero di targa e nessun'altra entità. 
Sul veicolo le autorizzazioni sono tutte attivate e da app è tutto funzionante. Quale potrebbe essere il problema?

![Screenshot 2023-12-09 084828](https://github.com/DurgNomis-drol/ha_toyota/assets/59484530/0e76a984-5514-4156-97fe-8703f9242a09)
![Screenshot 2023-12-09 085408](https://github.com/DurgNomis-drol/ha_toyota/assets/59484530/93b2555d-cb32-4625-9540-bfd86bb54947)

**Comment by CM000n** [comment]
Sorry, I don't understand Italian.

**Comment by Andream69** [comment]
> Mi spiace, non capisco l'italiano.

I installed everything as per procedure (Hacs) but I can only see the license plate number and no other entities. The permissions on the vehicle are all activated and the app is fully functional. What could be the problem?

**Comment by CM000n** [comment]
> I installed everything as per procedure (Hacs) but I can only see the license plate number and no other entities. The permissions on the vehicle are all activated and the app is fully functional. What could be the problem?

Please look here: https://github.com/DurgNomis-drol/ha_toyota/issues/164

This is currently a known issue due to Toyota's recent API changes. We are already working on an adaptation to the latest API. But this might take some time, as there is no public documentation and a lot is trial and error.

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊

**Comment by trytogetme85** [comment]
still same issue with 2.0.0

**Comment by CM000n** [comment]
> still same issue with 2.0.0

Please open a new issue if this is the case so that we can better understand and track it.
