### ISSUE TITLE
binary_sensor.yaris_cross_over_all_status 'problem'

### ISSUE THREAD

**Issue by BertVereecke** [DurgNomis-drol/ha_toyota#146]
Once in a while I see that the binary_sensor.yaris_cross_over_all_status changes its state to 'Problem'.
Using the mytoyota python library, I found out today that the Toyota server returned the following:
   'overallStatus': 'DRIVING'
This is the expected state, as my wife was driving the car at that moment.

I believe this 'problem' state is caused by the limitations of the binary_sensor.
Can this sensor perhaps be updated to a regular sensor, and simply report the state without changing it?

Kind regards,
Bert

**Comment by DurgNomis-drol** [comment]
Thanks for the bug report, when i coded this, this was not a feature.

The binary sensor needs to be converted to a normale sensor instead. PR's are more the welcome :)

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
