### ISSUE TITLE
Login (USA)

### ISSUE THREAD

**Issue by dkornahrens** [DurgNomis-drol/ha_toyota#153]
Is it not possible for those of us in the US to utilize this HA integration?  I tried to login using the Europe region still, thinking it may work across DC's, but it did not allow me to login.  Secondly, I have a Lexus, but the Toyota application works just fine for me with the same login as the Lexus application I created.

**Comment by DurgNomis-drol** [comment]
There was an North American version of this, but it got DMCA but Toyota American. This only works for Europe
