### ISSUE TITLE
Add Lexus brand

### ISSUE THREAD

**Issue by Paja-git** [DurgNomis-drol/ha_toyota#154]
As the parent development 'mytoyota' supports Lexus brand now, could you consider the addendum to the HA?

**Comment by migusan34** [comment]
That would be great ! Thanks !

**Comment by DurgNomis-drol** [comment]
I don't own an Lexus, so it would be impossible for me to support it. If someone wants to make a PR the makes it work, they are more then welcome!

**Comment by glowacki-dev** [comment]
I tried passing `brand="lexus"` to `mytoyota` constructor and was able to login and fetch all available data with this change https://github.com/glowacki-dev/ha_toyota/commit/1ecece83389eaecd4c162ca3e343df30fcbc4343

![image](https://github.com/DurgNomis-drol/ha_toyota/assets/2972266/f7a00d78-ff25-46a2-a758-76dec09b0a55)

I'll test this for a bit, but it looks promising and easy to add

**Comment by nrpetonr** [comment]
@glowacki-dev  does it still work for u?

**Comment by glowacki-dev** [comment]
Not anymore. It seems like lexus support was removed from recent versions of `mytoyota` package and will be brought back with https://github.com/DurgNomis-drol/mytoyota/pull/316.
I guess some current, relevant discussion is already ongoing here https://github.com/DurgNomis-drol/ha_toyota/discussions/218
