### ISSUE TITLE
device_tracker not working after HomeAssistant restart - unique_id issue?

### ISSUE THREAD

**Issue by pejotigrek** [DurgNomis-drol/ha_toyota#156]
**Describe the bug**
there is an error creating/refreshing device_tracker after HomeAssistant's restart. ofcourse entity exists - but it won't be updated. removing and reinstalling/reconfiguring integration helps. until next restart :( other entities are visible with no problem

related log entry:

`
2023-09-20 10:43:55.464 ERROR (MainThread) [homeassistant.components.device_tracker] Platform toyota does not generate unique IDs. ID ###REDACTED### parking location already exists - ignoring device_tracker.yaris_hybrid_premiere_edition_5h_b_parking_location
`

**To Reproduce**

1. Add integration
2. Configure account/add car
3. All entities work fine.
4. Restart HomeAssistant
5. See error, location no longer available

to undo the error:
1. Remove integration/configuration from dashboard
2. Restart HomeAssistant
3. Add/configure integration
4. No errors, until the restart

**Expected behavior**
No errors after restart, device_tracker working without issues.

**Additional context**
from the logs it looks like there's some issue with entity id maybe?

HomeAssistant version: 2023.9.2
Integration version: 1.2.11

**Comment by SrvRpi** [comment]
Same.

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
