### ISSUE TITLE
Not working with brand new RAV4 - UK

### ISSUE THREAD

**Issue by mwoodage** [DurgNomis-drol/ha_toyota#157]
I've just received my new RAV4 last week and struggling to get it to work with HA.
Everything appears to be setup correctly, but i'm getting the following error,

<img width="621" alt="Screenshot 2023-09-20 at 16 53 16" src="https://github.com/DurgNomis-drol/ha_toyota/assets/47755399/9ab4457c-786a-4a15-8d61-da302b0c0245">

<img width="554" alt="Screenshot 2023-09-20 at 16 58 49" src="https://github.com/DurgNomis-drol/ha_toyota/assets/47755399/2f2d9d25-8653-4815-b94f-eb68cc1cd2ef">

All the data seams to be coming through in relation to the model, registration, engine, but no other data like battery details, charging info, etc.
When I "add to the dashboard" nothing shows up.

<img width="358" alt="Screenshot 2023-09-20 at 17 02 49" src="https://github.com/DurgNomis-drol/ha_toyota/assets/47755399/f5e1cc49-4c94-4c2b-8d03-f3b1b12c35fd">

Am I doing something wrong or is there a bug with new cars?
The TY app is all setup and I get information from the car to the app.
HA is fully up to date.

Thanks in advance
M

**Comment by briandelicata** [comment]
Have the same issue with both my RAV4 PHEV and Yaris. Integration stopped working after being migrated from MyT Toyota app to the new MyToyota app.

**Comment by mwoodage** [comment]
Ah ok, I’ve just tried to set my car up on the old MyT app, but it says that my car can only use the new app. 
It would be amazing if someone can provide a fix 👍

**Comment by Chobnob** [comment]
The integration stopped working on my Rav4 when I moved to the MyToyota app from the MyT app. Presumably using the new app cause Toyota to upgrade the api for each user, that also prevents downgrading to the older MyT app.

**Comment by DurgNomis-drol** [comment]
#164
