### ISSUE TITLE
One Entity

### ISSUE THREAD

**Issue by Fran6u** [DurgNomis-drol/ha_toyota#159]
I am not sure if this can be considered a bug;
I am in Ireland and own a 2019 chr. I installed the addon via HACS, followed all the instructions but got just the one entity "numberplate". Any guidance is appreciated.

**Comment by s7relok** [comment]
Same here for my Yaris
Asked me to setup the car with the new application, and nothing apart the number plate appears

In the logs I have : ` Please setup Connected Services if you want live data from the car. (car serial here) `

These services are setup in the car, I did the pairing this morning

**Comment by Chobnob** [comment]
Likewise on my RAV4, just the numberplate. It appears that Toyota changes have broken the API.

**Comment by DurgNomis-drol** [comment]
#164
