### ISSUE TITLE
Location tracking sensor is gone. (EU)

### ISSUE THREAD

**Issue by finbom** [DurgNomis-drol/ha_toyota#162]
**Describe the bug**
Noticed recently that the sensor for location tracking of my RAV4 2022 not is working.
After trying to remove and reinstall the Toyota integration, the location sensor is not even listed any longer.
In the mobile app for MyToyota I can still track my car so the data is still collected, just not discovered by the integration.

**To Reproduce**
Location tracking is showing unavailable.
If removing the integration and adding it again, it is not even discovered as a sensor.

**Expected behavior**
A tracking sensor for the car GPS should list the car GPS position.
This information is found in the MyToyota app on mobile phone.

**Comment by m-dietrich** [comment]
I can confirm the problem from mys side.

I have the same problem since today.
Some sensors has gone unavailable, i have errors for "current_week_statistics" within the log, but no errors for location.
After removing and adding again, the error for "current_week_statistics" is still existing. Also, location-sensor is gone, or has not been discovered while re-adding the integration.

**Comment by m-dietrich** [comment]
After Building up a dev-environment, i tested again with the new installation.
All mentioned sensors available within there.

After that, i rechecked my live-environment.
Rechecked integration, and found all sensors available.
So there may be no real problem.

I will investigate this further, and provide additional informations, if needed.

**Comment by DurgNomis-drol** [comment]
Toyota is migrating to a new app, if you are using the new app this integration does not work anymore.

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
