### ISSUE TITLE
Ignore location updates when reporting 999.0,999.0

### ISSUE THREAD

**Issue by skgsergio** [DurgNomis-drol/ha_toyota#176]
**Is your feature request related to a problem? Please describe.**
Under some circumstances, the lat/long is reported as 999.0,999.0 which results in the following track in Home Assistant's Map Card:

![image](https://github.com/DurgNomis-drol/ha_toyota/assets/186349/be835935-41ed-4f8f-b584-03b11a6e89cb)

Toyota's app says that when it is running the location is unavailable and doesn't show it so I guess that is when it is reporting that bogus lat/lng.

**Describe the solution you'd like**
If the location is 999.0,999.0 the sensor shouldn't be updated, or in any case update it as "unknown".

**Describe alternatives you've considered**
N/A.

**Additional context**

Using directly the `mytoyota` python lib this is the content of the `vehicle._status`:

```sh
(mytoyota) sconde@setebos ~/tmp $ python toyota.py 
vehicle._status = {'event': {'lat': '999.0', 'lon': '999.0', 'timestamp': '1700479097000'}, 'tripStatus': '0'}
```

**Comment by CM000n** [comment]
We recently released version 2.0.0 of the Custom Component with major changes and support for the new Mytoyota API.
As we unfortunately cannot provide support for Custom Component versions < v2.0.0, I hereby close your issue.
If the issue still applies to the current version, you are of course free to open a new issue. 😊
