### ISSUE TITLE
No Sensordata but "Numberplate"

### ISSUE THREAD

**Issue by pc-bastler** [DurgNomis-drol/ha_toyota#184]
**Describe the bug**
I have a 2019 Corolla. I know this car doesn't deliver as much sensordata as actual cars, but I thought, I get at least the same info as with the Toyota native app.

**Expected behavior**
The only sensor I get after entering my credentials is the "corolla.nuberplate" with its attributes. I expected to have at least these addtl. sensors (since that is the information the native app shows also):

- sensor.corolla_odometer
- sensor.corolla_current_week_stats
- sensor.corolla_current_month_stats
- sensor.corolla_current_year_stats
- device_tracker.corolla

BTW: I am using the "new" App from Toyota if this makes any difference.

**Comment by ReneKorevaar** [comment]
I have the same problem   Please Help !

**Comment by CM000n** [comment]
Pleased look at:
https://github.com/DurgNomis-drol/ha_toyota/issues/164

We are currently working in supporting the new API Endpoints: https://github.com/DurgNomis-drol/mytoyota/pull/242

For the time being, you can download a version with a hotfix manually from the master branch.
However, this only works for the Numberplate and the statistics sensors. And nobody knows for how long, as the old API endpoints can be switched off at any time.
