### ISSUE TITLE
Only one entity instead of 26 entities since one week

### ISSUE THREAD

**Issue by Anangaranga** [DurgNomis-drol/ha_toyota#189]
**Describe the bug**
Last week, I have some entities from my Toyota Yaris. But, now, I have only one entity (licence plate).

There will a new update from app MyT to My Toyota.

Is this linked?

Thanks for your help.

**Comment by jee67** [comment]
Same here for RAV4

**Comment by CincioToby** [comment]
same only licence plate.

**Comment by lexlutor72** [comment]
Same here for C-HR.

**Comment by thmz82** [comment]
This is related to a breaking change in the Toyota API that occurs when you move from the old "MyT" app to the new "MyToyota" app. See also issue https://github.com/DurgNomis-drol/ha_toyota/issues/164

Short summary: work on the necessary library is in progress and it looks good that it could be updated in the near future.

**Comment by Anangaranga** [comment]
> This is related to a breaking change in the Toyota API that occurs when you move from the old "MyT" app to the new "MyToyota" app. See also issue #164
> 
> Short summary: work on the necessary library is in progress and it looks good that it could be updated in the near future.

Ok, thanks for your help 👍
