### ISSUE TITLE
Only create a battery health sensor if there is information available for it

### ISSUE THREAD

**Issue by CM000n** [DurgNomis-drol/ha_toyota#19]
**Describe the bug**
With the latest version of HA Toyota it generates a battery health sensor although, as far as I know, in the case of my vehicle Toyota does not provide any information for it.

**To Reproduce**
You must own a Toyota Corolla and set up the latest version (2.0) of HA Toyota ;-)

**Expected behavior**
Only create sensors for which information is also provided by the vehicle. If the vehicle does not provide the information, do not create a sensor for it.

**Screenshots**
![094732094732nt](https://user-images.githubusercontent.com/7945681/113430012-b3e13800-93d9-11eb-87e3-cea7bbfb6cd3.PNG)

**Comment by DurgNomis-drol** [comment]
Maybe only combustion engine cars implement this feature, and EV's and hybrids doesn't. I will make it so that it should only generate it if the attribute is available 😊

**Comment by DurgNomis-drol** [comment]
@CM000n  also when you use the `tojota` script, did you get any information returned for your EV battery?

**Comment by CM000n** [comment]
As you can see from our discussion over at your mytoyota repo, these are the only informations I currently get for my vehicle:
https://github.com/DurgNomis-drol/mytoyota/issues/10#issuecomment-808941237

**Comment by DurgNomis-drol** [comment]
A fix is pushed 😄

**Comment by CM000n** [comment]
Confirmed. Now it works as it should.
Thanks for the fix and happy easter holidays (if you have them in Denmark right now too ;-) )

**Comment by DurgNomis-drol** [comment]
Great to hear!

Thanks, yes we have and you too 😄
