### ISSUE TITLE
ha_toyota seems to wont be loaded

### ISSUE THREAD

**Issue by saintfrater** [DurgNomis-drol/ha_toyota#199]
**Describe the bug**
I've reinstalled several time both ha_toyota and connected service without success....

the only log I get is the following (in debug)

_2024-01-05 21:32:50.689 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 1.158 seconds (success: False)_

**Expected behavior**
at least some log to help about the issue

**Additional context**

**Comment by CM000n** [comment]
Duplicate. Please look at: https://github.com/DurgNomis-drol/ha_toyota/issues/160
