### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by raffaelevall** [DurgNomis-drol/ha_toyota#20]
Hi, congrats for this great work.
I download the zip file and extract it, then copy the "toyota" folder from ha_toyota-master\ha_toyota-master\custom_components\toyota and paste it to my custom_components folder in HA.

Restart Home Assistant

If I go to configuration - Integrations - Add Integration and search for “Toyota Connected Services” I found "Mazda Connected Services”"

![image](https://user-images.githubusercontent.com/57603062/113437100-50113c00-93e6-11eb-99e0-2d5fb12f606e.png)

Tks a lot

Raffaele

**Comment by DurgNomis-drol** [comment]
Have you just tried searching for "Toyota"? Also can you check your logs if something have gone wrong? 😊

Thanks for the feedback

**Comment by raffaelevall** [comment]
If I search only for "Toyota" ....nothing found :-)

![image](https://user-images.githubusercontent.com/57603062/113438107-37098a80-93e8-11eb-858e-ec31a1a0eb02.png)

No errors in the logs 

Tks a lot for your reply

**Comment by DurgNomis-drol** [comment]
Can you check if your folder structurer is correct? Make sure that `toyota` folder is placed under `custom_components` folder and that the `custom_components`is placed in `/config`. Your full folder path should be `/config/custom_components/toyota` where `/config` is the folder that `configuration.yaml` is in.

If this is correct, under the logs tab, you can choose "View full Homeassistant log" and this should show  more details. 😊

**Comment by raffaelevall** [comment]
Sorry my friend,
I have to restart the VM in Proxmox installation and the integration works fine:

![image](https://user-images.githubusercontent.com/57603062/113440768-548d2300-93ed-11eb-861e-c31dd1ff48ba.png)
only the "sensor.c_hr_starter_battery_health" is "unknown"

thanks again and tell me if i can do something to help you in your great work

**Comment by DurgNomis-drol** [comment]
No problem 😁

About the sensor showing `unknown` it is a bug #19 I will fix this soon. 

Can you tell what model you have?

**Comment by raffaelevall** [comment]
It's hybrid 😁 
Tks again
