### ISSUE TITLE
App requires a confirmation code

### ISSUE THREAD

**Issue by npelto** [DurgNomis-drol/ha_toyota#207]
**Describe the bug**
I try to sign in with my MyToyota credentials, but I get an error `invalid_auth`
I also receive a six digit confirmation code to my email.

**To Reproduce**

1. Reinstall Toyota Connected Services Integration
2. Input email and password
3. See error
4. Receive email with confirmation code

**Expected behavior**
I'd expect the authentication flow to display an input for the confirmation code if it's required.

**Comment by CM000n** [comment]
Hello @npelto, have you made sure that you are already using the latest [`MyToyota`](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu) app? It sounds like you are still using the old [`MyT`](https://[play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US)) app.

**Comment by npelto** [comment]
Oh that did it!

I don't think that's mentioned in the readme or changelog.

**Comment by CM000n** [comment]
> Oh that did it!
> 
> I don't think that's mentioned in the readme or changelog.

It's in the Changlog @npelto! One of the first sentences:
https://github.com/DurgNomis-drol/ha_toyota/releases/tag/v2.0.0

 Seems like you didn't read it as carefully as you might think 😉
