### ISSUE TITLE
I get error 13 permission denied on .cache

### ISSUE THREAD

**Issue by disi** [DurgNomis-drol/ha_toyota#208]
**Describe the bug**
I get error 13 permission denied on '.cache'

**To Reproduce**

1. Add 2.0 via HACS
2. Restart Home Asisstant
3. Setting Devices -> Add Integration and enter credentials
4. ERROR (MainThread) [custom_components.toyota.config_flow] An unknown error occurred during login request: [Errno 13] Permission denied: '.cache'

**Expected behavior**
Add my account to the integration.

**Screenshots**
ERROR (MainThread) [custom_components.toyota.config_flow] An unknown error occurred during login request: [Errno 13] Permission denied: '.cache'

**Additional context**
This is 2024.1.2 run as docker version.

I only found the .cache folder directly under /hass_config/.cache and tried to rremove, reinstall through HACs, there are subfolders named 'pip' and 'http' in there. I am not sure, I am looking the the correct folder.

**Comment by CM000n** [comment]
Hi @disi. The `.cache` folder is created in the home directory of the Docker container user. In my case, for example, this is the `/root` directory within the container:

![Screenshot 2024-01-15 105529](https://github.com/DurgNomis-drol/ha_toyota/assets/7945681/048af890-2c99-48bf-a019-d99cd66e2754)


Strange, actually the container user should also have the right to write to his home directory. Or are you running the Home Assistant process yourself via another user?

**Comment by disi** [comment]
I tried recreating it:
```
[root@dombox hass_config]# mkdir .cache
[root@dombox hass_config]# chown -R 911:911 .cache/
[root@dombox hass_config]# ls -la .cache
total 4
drwxr-xr-x.  2 911 911    6 Jan 15 10:48 .
drwxr-xr-x. 15 911 911 4096 Jan 15 10:49 ..
```
Everything under hass_config is owned by 911.
And restarted the entire homeassistant container, same error.
Even changing 777 on the folder, gives the same error.
Starting homeassistant without the folder, same error.
![container](https://github.com/DurgNomis-drol/ha_toyota/assets/877046/339f24c3-0faf-4910-8fff-8923099cd592)

**Comment by CM000n** [comment]
The .cache folder is, as already written, not created in the config directory of your Home Assistant, but in the home directory of the user with whom the Home Assistant process is executed!
So it has nothing to do with your `/hass_config` folder 😉

**Comment by disi** [comment]
I don't understand where else it would look for it.
In the setup I have:
All files are written by the user "abc" from within the container with user id 911.
Its home directory is /config inside the container.
/hass_config on the host system is mapped as /config into the container.
So I believe the .cache folder should be in /hass_config/.cache or within the container /config/.cache.

There was a folder with this name before and permissions 911:911, I even tried to change it with all write permissions, and tried recreating the folder.

I get the user input form from config_flow.py, I enter my credentials, no matter if correct or not I get the error about permissions on .cache when I hit Submit.

**Comment by CM000n** [comment]
> p.s. going back to 1.3, it creates the .cache folder where I expected it and create some subfolder /config/.cache/pip

That makes absolutely no sense. Version 1.3 never created a `.cache` folder itself. Especially not for pip files. This has nothing to do with each other.

What does your docker-compose file look like, if you have one?

What is the user behind the id 911? 
`id -nu 911`
An attempt is made to create the .cache folder in its home directory:
`eval echo ~<User ID from command above>`

**Comment by disi** [comment]
V 1.3
2024-01-15 13:27:52.001 INFO (SyncWorker_10) [homeassistant.util.package] Attempting install of mytoyota==0.9.3
installed to /config/.cache/pip
v 2.0
2024-01-15 13:31:29.559 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of mytoyota>=1.2.0
installed to /config/.cache/pip

But with 1.3 I do not get the .cache error as in 2.0.

**Comment by CM000n** [comment]
> V 1.3
> 2024-01-15 13:27:52.001 INFO (SyncWorker_10) [homeassistant.util.package] Attempting install of mytoyota==0.9.3
> installed to /config/.cache/pip
> v 2.0
> 2024-01-15 13:31:29.559 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of mytoyota>=1.2.0
> installed to /config/.cache/pip
> I believe this is just a hash of the version installed of the python library of mytoyota.

You are mixing things up here. this is not a `.cache` folder that is created by the `mytoyota` lib itself, but a folder for caching pip files. This is handled entirely by the respective python env itself.

I don't want to be offensive, but you really have a very strange config of your container and home assistant 😉 

Sorry, but this looks to me less like a actual problem with the `mytoyota` Python lib and more like a misconfiguration of the linux permissions. What is the user of your home assistant process when you enter `top` in your container? 

```bash
Mem: 15837116K used, 179316K free, 6001648K shrd, 411572K buff, 13050220K cached
CPU:   3% usr   1% sys   0% nic  89% idle   5% io   0% irq   0% sirq
Load average: 0.14 0.25 0.33 3/843 246
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  173    64 root     S    1419m   9%   1   1% python3 -m homeassistant --config /config
  230     0 root     S     2592   0%   0   0% bash
  239     0 root     S     2592   0%   0   0% bash
  246   239 root     R     1600   0%   3   0% top
   24     1 root     S      212   0%   1   0% s6-supervise s6rc-fdholder
   15     1 root     S      212   0%   1   0% s6-supervise s6-linux-init-shutdownd
   25     1 root     S      212   0%   0   0% s6-supervise s6rc-oneshot-runner
   64     1 root     S      212   0%   2   0% s6-supervise home-assistant
    1     0 root     S      208   0%   3   0% /package/admin/s6/command/s6-svscan -d4 -- /run/service
   17    15 root     S      200   0%   3   0% /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   33    25 root     S      188   0%   0   0% /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /p
home-assistant:/config
```

**Comment by disi** [comment]
This works:
```
[root@dombox ~]# podman exec -it homeassistant /bin/bash
root@dombox.dom:/# sudo -S -u abc python
Python 3.11.6 (main, Oct  4 2023, 06:22:18) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> CACHE_FILENAME: Path = Path.home() / ".cache" / "toyota_credentials_cache_contains_secrets"
>>> CACHE_FILENAME.parent.mkdir(parents=True, exist_ok=True)
>>> with open(str(CACHE_FILENAME), "w", encoding="utf-8") as f:  f.write(  json.dumps(  {   "access_token": "None",   "refresh_token": "None",   "uuid": "None",     "expiration": "None",    "username": "None",   },    default=str,    )  )

```
File is created with content.
```
[root@dombox ~]# ls -la /stratis/hass_config/.cache/
total 8
drwxr-xr-x.  2 911 911   55 Jan 15 15:29 .
drwxr-xr-x. 16 911 911 4096 Jan 15 15:38 ..
-rw-r--r--.  1 911 911  107 Jan 15 15:35 toyota_credentials_cache_contains_secrets
```

**Comment by CM000n** [comment]
This looks good. But presumably setting up the custom component still fails, I assume?

**Comment by disi** [comment]
OK!!!1111111elevenoneone

I was using the linuxserver.io home assistant image docker.io/linuxserver/homeassistant.
Now I switched to ghcr.io/home-assistant/home-assistant:latest

AND it works!
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/877046/2f15967d-86f1-4dce-a123-7fcfbacb2aaa)

Thank you for your patience :)

**Comment by CM000n** [comment]
Very nice! Good to see it works for you now 😊

**Comment by CM000n** [comment]
This all sounds like the Home Assistant process is being started by a user who does not have permission to create the `.cache` folder.

This depends heavily on your personal environment and configuration ACL permissions. 

Unfortunately, we can only help to a limited extent here, as we do not know and cannot understand your personal environments.

**Comment by jprihoda** [comment]
Hi, I'm having exactly the same issue. I have verified multiple times that my Home Assistant is running under the same user who owns the .cache directory in the home folder. Even changing the permissions of the .cache directory to 777 didn't resolve the issue. (HA Core 2024.1.3 python 3.11.3 venv)

**Comment by ingvarso** [comment]
Same issue for me as well. Using the linuxserver.io home assistant image. 

Tried the steps above and creating the file manually from python, and that works without errors.

**Comment by CM000n** [comment]
As already written above: https://github.com/DurgNomis-drol/ha_toyota/issues/208#issuecomment-1892348974
This is more a problem with the authorisation settings of the respective environment. We can only help to a limited extent here.

A user here also wrote that the problem was solved for him after switching from the unofficial linuxserver.io container to the official Home Assistant container. https://github.com/DurgNomis-drol/ha_toyota/issues/208#issuecomment-1892521098
