### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by bohmszi** [DurgNomis-drol/ha_toyota#209]
**Describe the bug**
I'm getting error ```Email/Password is incorrect``` during setting up the integration. I've used the previous MyT version before. I removed and recreated the folder in custom_components and also updated Home Assistant to the latest version. Also removed the integration in HA and tried to add it again. I'm using core ```2024.1.3```. I also verified my password by logging out and in again on my mobile app, which worked.

**To Reproduce**

1. Go to Integrations.
2. Click on Toyota Connected Services
3. Enter e-mail and password.
4. See error:
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/8437305/7650488d-aa54-48eb-a18b-df7295764f4a)
Log record in docker:
```2024-01-15 11:52:10.189 ERROR (MainThread) [custom_components.toyota.config_flow] Authentication Failed. Unknown method.```

**Expected behavior**
Integration to be completed.

**Screenshots**
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/8437305/7650488d-aa54-48eb-a18b-df7295764f4a)

**Additional context**
Home assistant core ```2024.1.3``` in docker. Frontend version```20240104.0```.

**Comment by CM000n** [comment]
Hi, are you already using the new MyToyota App from Toyota or do you still using the old MyT App?

**Comment by bohmszi** [comment]
Hello @CM000n, you are right, I used the old ```MyT Toyota``` application. I was a little bit confused since my API hasn't been working for a while with the old app, and it also had some changes in it's name, so I thought the app upgrade was done automatically.
Thanks for the heads-up, it works like a charm now!
