### ISSUE TITLE
Unable to add Integration/Device

### ISSUE THREAD

**Issue by phoo8ar** [DurgNomis-drol/ha_toyota#210]
**Describe the bug**
Trying to add myToyota account gives Email/Password is incorrect AND with a side effect that sends a 2FA password (6 digit number) to email address from no-reply@toyotaconnectedeurope.io
I cannot find anything like 2FA settings in the account settings on the web at. 

**To Reproduce**

1. Go to +Add Integration
2. Search for Toyota Connected Services
3. Input user credentials as: "Please input your email and password for MyT below."
4. "Email/Password is incorrect"

**Expected behavior**
New device added 

**Screenshots**
See included screenshot
[myT.pdf](https://github.com/DurgNomis-drol/ha_toyota/files/13941510/myT.pdf)

**Additional context**
Core 2024.1.3, Supervisor 2023.12.0, Operating System 11.4, Frontend 20240104.0
Toyota Connected Services ver 2.0.0

**Comment by CM000n** [comment]
Hi @phoo8ar. Looks like you didn't read the release notes properly 😉 
Have you made sure that you are already using the latest [`MyToyota`](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu) app before updating? It sounds like you are still using the old [`MyT`](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota) app.

See also: https://github.com/DurgNomis-drol/mytoyota/issues/277

**Comment by phoo8ar** [comment]
my bad, it's working now.
thank you for your effort
