### ISSUE TITLE
Validation errors for `VehicleResponseModel`

### ISSUE THREAD

**Issue by 0p3t0** [DurgNomis-drol/ha_toyota#211]
Dear @CM000n, 
Unfortunately I had read the changelog and perform 2 cleanup with full host reboot, before commenting, but I'm sad still not working.

I've deleted the HA Integration
![image](https://user-images.githubusercontent.com/59409205/296857162-e137ad11-5c7b-44e1-aace-b8728a43381b.png)

Removed integration from HACS
![image](https://user-images.githubusercontent.com/59409205/296857245-fc400d88-2e21-422d-a946-09f52eefad13.png)

Verified that in custom_components the folder /config/custom_components/toyota was not present.
Perform a full host reboot
Installed from HACS
![image](https://user-images.githubusercontent.com/59409205/296858281-88ad6d1c-97d4-418f-bc8c-f43eaef2e6a0.png)

Installed integration
![image](https://user-images.githubusercontent.com/59409205/296858943-6710f3bc-8ce8-43b9-8b67-1fc16390ecac.png)
but same behavior after login
![image](https://user-images.githubusercontent.com/59409205/296858993-88a943a6-c034-4c8e-b7b8-2be91847bc24.png)
![image](https://user-images.githubusercontent.com/59409205/296859032-f54a9dc7-6b42-4717-88d6-ff43d2b8279c.png)
and trying to select "configure" show this message
![image](https://user-images.githubusercontent.com/59409205/296859104-14546216-29b9-47cc-a21c-f84c45c25eb8.png)

Please let me know if I can help in other way, and I appreciate if you reopen issue #160 so we can add all relevant information there.
I'm glad to help if possible, but do not think I didn't perform all tests before writing :D 
Thanks a lot!
>
                > Unfortunately also with v2.0.0 still not working ![image](https://private-user-images.githubusercontent.com/59409205/296782683-f8c3660d-daee-40b0-9899-f94af049e36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzE3MDIsIm5iZiI6MTcwNTMzMTQwMiwicGF0aCI6Ii81OTQwOTIwNS8yOTY3ODI2ODMtZjhjMzY2MGQtZGFlZS00MGIwLTk4OTktZjk0YWYwNDllMzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE1MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzg0ZTkyMWYxMDM0OWQyZjUwYjIyMGFlODY0MDEwYTlhZTI5NWVhYWVkZjZiNThmOGJhZDQyZWZkMjJhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aqlz1y3c5e3qYQ4640CG2UXbfv1D62zd_CBnR3ItAZg)
  
  > Someone else who hasn't read the changelog properly https://github.com/DurgNomis-drol/ha_toyota/releases/tag/v2.0.0 😉 😛
  
  > _Originally posted by @CM000n in https://github.com/DurgNomis-drol/ha_toyota/issues/160#issuecomment-1892353695_

**Comment by CM000n** [comment]
This is a completely new error and has to do with an incompatibility of your vehicle with the pydantic models we use for the `mytoyota` lib.
This means that the error must also be rectified there. 
Thank you for your notification and detailed error description

**Comment by CM000n** [comment]
Really interesting @0p3t0, you're the first one who didn't get any basic car information back from the API endpoints.
Can you perhaps provide some more information about your vehicle and a screenshot from the original Toyota app?

**Comment by Darka920** [comment]
Hey,
I had exactly the same problem. I think the problem was that there was two cars registered in app. Even though it said both cars were migrated it somehow still failed. 
I have download old app, logged in, got error that both cars were migrated and i should use new app. When I opened new app it said that one of the cars did not have active "Connected Services Centre". After I activated it everything works fine.

**Comment by CM000n** [comment]
Thank you for reporting @Darka920. I was already thinking something like that, as it is really basic information that does not arrive in the pydantic model for @0p3t0.
Can you please check whether the same case as for @Darka920 also applies to yourself @0p3t0?

**Comment by 0p3t0** [comment]
Dear @CM000n , @Darka920 , I had exactly same issue, removing the other veichle seems the integration started properly, now I can see integration starting properly and some data are available.
I'll have a look this evening to check the update of the data, but I'm pretty sure everything is now clear about the error.
Thanks a lot for the great job! 
I'm glad to help if any additional tests are required, of course =)

**Comment by CM000n** [comment]
Nice to hear that 😊 
I am closing this because the error is not on our side but because a faulty/incomplete migration of the vehicle to the new API
