### ISSUE TITLE
"Use metric units" toggle has no effect

### ISSUE THREAD

**Issue by ccristal** [DurgNomis-drol/ha_toyota#217]
**Describe the bug**
Even though I switch off the "Use metric units" toggle during the first configuration, sensor values are still expressed in metric units.

**To Reproduce**

1. Settings -> Devices & Services
2. Add Integration
3. Select "Toyota Connected Services"
4. Enter MyT email and password
5. Switch off the "Use metric units" toggle
6. Click "Submit":
7. Click "Finish"
8. On the Toyota Connected Service tile, click on "1 device"
9. Observe that all the numeric values for the Sensors are expressed in Km:

**Expected behavior**
The sensor values should be expressed in miles.

**Screenshots**
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/5416417/a4b02172-84ed-4917-b288-6ba150fa7c29)
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/5416417/b4696909-3120-4dde-bf16-d66be2efb309)

**Additional context**

**Comment by CM000n** [comment]
That is strange. I'll have a look at it. Thank you for reporting it.

**Comment by CM000n** [comment]
Hi @ccristal. This seems to be a issue of the category "It's not a bug, it's a Feature!" 😆 

I have looked at our code and could not find any errors. The switch does exactly what it is supposed to do. Depending on the selection, the `mytoyota` python lib returns either metric or no metric values.

The "problem" lies with Home Assistant itself. Depending on the settings for Home Assistant, the units are converted automatically! 
However, this can also be overwritten later in the settings of the respective sensors:
![Screenshot 2024-01-11 162827](https://github.com/DurgNomis-drol/ha_toyota/assets/7945681/51b1e267-415e-4780-bebd-6d7b09d80391)

I think I have also found a setting option that allows you to specify the units with which a sensor should initially be displayed.
This should be included in the next release 😊 
In the meantime, you can simply set your sensors to the desired display format yourself 😉

**Comment by ccristal** [comment]
Thank you for looking into this... :-)
