### ISSUE TITLE
Email/Password is incorrect.

### ISSUE THREAD

**Issue by Buktahula** [DurgNomis-drol/ha_toyota#22]
**Describe the bug**
I always get the message "Email/Password is incorrect." but E-Mail and Password are correct.

**To Reproduce**

1. I start the integration 
2. fill in all my data
3. klick on login
4. Email/Password is incorrect.

**Expected behavior**
I always get the message "Email/Password is incorrect." but E-Mail and Password are correct.
![Unbenannt](https://user-images.githubusercontent.com/54060176/116655451-68478d00-a98b-11eb-8baa-9d5894d9f5c0.PNG)

**Comment by Buktahula** [comment]
I found the solution , i have to write de-DE to the Language code not de-de

**Comment by DurgNomis-drol** [comment]
I unfortunately have not found a way to handle language automatically. But glad to here you found a solution. 😊
