### ISSUE TITLE
status=403, error="Forbidden", message="Verification is missing.", errorCode="CMA403"

### ISSUE THREAD

**Issue by andras-tim** [DurgNomis-drol/ha_toyota#221]
**Describe the bug**
The last time, when I visited my Toyota service, they told me the [MyT app](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota) is deprecated, and I must use the new [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu). Unfortunately, since I logged into the new app, this integration is constantly failing because of this error:

```
Logger: custom_components.toyota
Source: helpers/update_coordinator.py:266
Integration: Toyota Connected Services ([documentation](https://github.com/DurgNomis-drol/ha_toyota), [issues](https://github.com/DurgNomis-drol/ha_toyota/issues))

Error fetching toyota data: HTTP: 403 - {"timestamp":1705692817166,"status":403,"error":"Forbidden","message":"Verification is missing.","errorCode":"CMA403"}
```

I tried to re-add the integration, but after the successful login, the integration still drops the same error.

**To Reproduce**

1. Login once into the new [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu) app.
2. Wait for a while, and the integration will not download the data

**Screenshots**
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/619016/c400d1bb-809d-493d-8043-ff4fc41f88f0)

**Additional context**
Home Assistant 2023.9.3
Frontend 20230911.0 - latest

ha_toyota: 1.2.11

**Comment by CM000n** [comment]
Please usw the current version of the Custom Component 😉 

Version < 2.0 only supports vehicles that are registered with the MyT App. Since version >= 2.0 WE are only supporing vehicles from the MyToyota App.

**Comment by andras-tim** [comment]
Dear @CM000n,

I created the issue weeks later than I faced with the problem, and at that time the v2 didn't exist... Wow! 😲  

This works like a charm!
Thank you so much!
