### ISSUE TITLE
After Core update 2024.1.5 Failed setup

### ISSUE THREAD

**Issue by AdrianStanciu22** [DurgNomis-drol/ha_toyota#223]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by CM000n** [comment]
Can you please add more information.
What is the exact error message? Do you have any log information?

**Comment by AdrianStanciu22** [comment]
Works again.

**Comment by AdrianStanciu22** [comment]
Works again
