### ISSUE TITLE
Enhancement: Set Sensordata to 0 (Zero) instead of "Unknown"

### ISSUE THREAD

**Issue by pc-bastler** [DurgNomis-drol/ha_toyota#224]
**Is your feature request related to a problem? Please describe.**
If a sensor has no data yet it is reported as "unknown" in HA. I.e. the daily statisics (sensor data and its attributes) is reported "unknown" until I took the first ride.

**Describe the solution you'd like**
Fpr the statics it would be great, if there would be reported a 0-value the graphs would look much nicer ("Zero-Bars" instead of nothing)

**Comment by CM000n** [comment]
Even if this sounds understandable at first glance, I'm honestly not in favor of it.
We don't have the API under control and everything we know has come about through trial and error and guesswork.
So we can never be sure of the current values. A None value (unknown) is therefore more honest than a 0 value and does not distort the statistics if you want to carry out further aggregations based on the data collected.
As an emergency solution, you could help yourself with a template sensor if it bothers you a lot.

**Comment by DurgNomis-drol** [comment]
We should always follow the HA architecture. (The HA way if you would). Though I understand your probkem, and somewhat agree with you, there isn't a good way to handle this in the right way other the following HA design rules.
