### ISSUE TITLE
Failed to add integration

### ISSUE THREAD

**Issue by mirkocampisi** [DurgNomis-drol/ha_toyota#227]
I can't configure the integration. I add username and password but says "unknown error occurred". I'm using MyToyota app on IOS.

Home Assistant

Core
2024.1.5
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

See pictures.

Thanks.

Mirko

![Acquisizione schermata 23 01 2024 alle 10 47 01](https://github.com/DurgNomis-drol/ha_toyota/assets/74451235/344be941-374b-4aba-a6cf-e479e3fa7599)
![Acquisizione schermata 23 01 2024 alle 10 45 35](https://github.com/DurgNomis-drol/ha_toyota/assets/74451235/ab7c58df-fa3b-47b2-bd36-70c862308083)

**Comment by CM000n** [comment]
Sorry, but this picture alone doesn't say much. Do you have any more information from the logs?

Have you made sure that you are already using the **latest** [`MyToyota`](https://apps.apple.com/de/app/mytoyota/id1617623127) app before updating and not the old [`MyT`](https://apps.apple.com/at/app/myt-by-toyota/id1020262732) app?

See also: https://github.com/DurgNomis-drol/ha_toyota/releases/tag/v2.0.0

There has already been some feedback here from people who did not read the release notes properly and were still using the old MyT app before the update. The error pattern was similiar for them.

**Comment by mirkocampisi** [comment]
Sorry I didn't tell this before... Yes I'm using the new MyToyota app (the black one).

Unfortunately the only log that says something is the Home Assistant Core log (the one I posted)

**Comment by mirkocampisi** [comment]
Never mind, I used the wrong email address :D

I expected wrong email or password error but now it works...

Thanks!
