### ISSUE TITLE
Always reports values in Metric

### ISSUE THREAD

**Issue by GitOldGrumpy** [DurgNomis-drol/ha_toyota#230]
**Describe the bug**

If you de-select the Metric option during Configuration(i.e. report in Miles) you still get Metric.

**To Reproduce**

Configure a vehicle using Imperial as opposed to Metric.

**Expected behavior**

I would expect to see Imperial measurements.

**Screenshots**
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/29694358/5c3c9f2e-a181-4508-ba45-75762ff54822)
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/29694358/645fe559-f85c-4bfe-af2d-44da63f46052)

**Comment by CM000n** [comment]
Please see https://github.com/DurgNomis-drol/ha_toyota/issues/217
