### ISSUE TITLE
expected string or bytes-like object, got 'list'

### ISSUE THREAD

**Issue by vladurash** [DurgNomis-drol/ha_toyota#233]
**Describe the bug**
Toyota EU integration in HA return error "Failed setup, will retry". As additional error message I found this

expected string or bytes-like object, got 'list'

**To Reproduce**

1. Go to (homeassistantIP:8123/config/integrations/integration/toyota)
2. See error

**Expected behavior**
Expected is to work

**Screenshots**
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/73290807/86761240-109e-4985-9932-911caac7db79)

**Additional context**
Latest integration version. I erased it from HACS and checked in custom_components folder for any remained files.
Restarted HA, installed again integration. Same behaviour.
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/73290807/0f2a7e43-98be-4499-904a-603f0a247bb3)

**Comment by CM000n** [comment]
Which Version of mytoyota is installed on your Home Assistant?
With mytoyota v2.0.0 there should be already a fix for this: https://github.com/DurgNomis-drol/mytoyota/pull/319

**Comment by CM000n** [comment]
I just released a new version which pins the used mytoyota version to 2.0.0:
https://github.com/DurgNomis-drol/ha_toyota/releases/tag/v2.0.1

Can you please test and report back, if it works for you?

**Comment by vladurash** [comment]
Updated to 2.0.1 and now it works ok. Thanks.

**Comment by vladurash** [comment]
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/73290807/56143e1c-aac6-4d8a-8c55-6fa2d5c6b697)

**Comment by CM000n** [comment]
Thx for checking!
