### ISSUE TITLE
No device or entities

### ISSUE THREAD

**Issue by tomasb82** [DurgNomis-drol/ha_toyota#248]
The integration creates entry but no devices or entites are creared. 

Cars bz4x and Rav4. 

![Screenshot_20240323_210447_Home Assistant](https://github.com/DurgNomis-drol/ha_toyota/assets/74060061/ad25eac3-07da-4f90-b5d4-b94b6f1b62cb)

**Comment by briandelicata** [comment]
Haave the same issue with RAV4 & Yaris.

**Comment by CM000n** [comment]
Have your vehicles already been migrated to the new Toyota API?
Or to put it another way, are you still using the old [MyT app](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US), or are you already using the current [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu&hl=de_CH)?

**Comment by tomasb82** [comment]
yes, cars are in a new app.

In logs were is no erros abuot a toyota integration.

**Comment by briandelicata** [comment]
> Have your vehicles already been migrated to the new Toyota API? Or to put it another way, are you still using the old [MyT app](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US), or are you already using the current [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu&hl=de_CH)?
> 
> I will release a new version soon, which will hopefully fix the logging within Home Assistant. Please have a look if you can find something in the logs then.

Yes both my cars are on the new app and it was working with the latest release until a few weeks ago. Running mytoyota package with full logging, I notice that both cars are retrieved together with their data however the script thjrows the following error:

pydantic.error_wrappers.ValidationError: 1 validation error for ElectricResponseModel
payload -> evRangeWithAc
  field required (type=value_error.missing)

**Comment by CM000n** [comment]
> > Have your vehicles already been migrated to the new Toyota API? Or to put it another way, are you still using the old [MyT app](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US), or are you already using the current [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu&hl=de_CH)?
> > I will release a new version soon, which will hopefully fix the logging within Home Assistant. Please have a look if you can find something in the logs then.
> 
> Yes both my cars are on the new app and it was working with the latest release until a few weeks ago. Running mytoyota package with full logging, I notice that both cars are retrieved together with their data however the script outputs the following error:
> 
> pydantic.error_wrappers.ValidationError: 1 validation error for ElectricResponseModel payload -> evRangeWithAc field required (type=value_error.missing)

Thank you, that helps!
It looks like Toyota has adapted their API again and we have to adapt one of the models in the mytoyota package. 😞

**Comment by mork993** [comment]
I'am having the same problem :(

**Comment by manelmg** [comment]
Same Issue.
I am using new MyToyota app with Rav4 Plug-in.

**Comment by CM000n** [comment]
We need a little help with the development here.
Since none of the current developers own a fully electric vehicle or a plug-in hybrid, we can only guess the model for the EV API interface.
It would be nice if someone with such a vehicle could take a look at the interface and tell us the current model: https://github.com/DurgNomis-drol/mytoyota/pull/340#issuecomment-2025180123

**Comment by tomasb82** [comment]
> Have your vehicles already been migrated to the new Toyota API? Or to put it another way, are you still using the old [MyT app](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US), or are you already using the current [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu&hl=de_CH)?
> 
> I will release a new version soon, which will hopefully fix the logging within Home Assistant. Please have a look if you can find something in the logs then.

Hi, after update still no devices are created.

**Comment by desosav** [comment]
> > Have your vehicles already been migrated to the new Toyota API? Or to put it another way, are you still using the old [MyT app](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US), or are you already using the current [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu&hl=de_CH)?
> > I will release a new version soon, which will hopefully fix the logging within Home Assistant. Please have a look if you can find something in the logs then.
> 
> Hi, after update still no devices are created.

Hi there, 
the latest update was targeting to fix the logging issue.
Now that this is resolved, you can check your Homeassistant logs and see if there are any errors related to the mytoyota integration. You can share your findings here and hopefully someone should be able to identify and fix what is blocking the integration from creating the necessary devices/entities in homeassistant.

**Comment by tomasb82** [comment]
> > > Have your vehicles already been migrated to the new Toyota API? Or to put it another way, are you still using the old [MyT app](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=US), or are you already using the current [MyToyota app](https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu&hl=de_CH)?
> > > I will release a new version soon, which will hopefully fix the logging within Home Assistant. Please have a look if you can find something in the logs then.
> > 
> > 
> > Hi, after update still no devices are created.
> 
> Hi there, the latest update was targeting to fix the logging issue. Now that this is resolved, you can check your Homeassistant logs and see if there are any errors related to the mytoyota integration. You can share your findings here and hopefully someone should be able to identify and fix what is blocking the integration from creating the necessary devices/entities in homeassistant.
> 
> By the way there is a pull request created, which once it is merged should fix the issue [DurgNomis-drol/mytoyota#340](https://github.com/DurgNomis-drol/mytoyota/pull/340)

This is errors what I get


2024-04-05 13:33:49.541 ERROR (MainThread) [custom_components.toyota] 1 validation error for VehiclesResponseModel
payload -> 0 -> dcm -> dcmSupplierName
  none is not an allowed value (type=type_error.none.not_allowed)
2024-04-05 13:33:49.541 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 0.910 seconds (success: True)

2024-04-05 13:33:55.604 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up toyota.binary_sensor
2024-04-05 13:33:55.604 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up toyota platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/binary_sensor.py", line 232, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2024-04-05 13:33:55.611 INFO (MainThread) [homeassistant.components.device_tracker] Setting up toyota.device_tracker
2024-04-05 13:33:55.611 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up toyota platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/device_tracker.py", line 39, in async_setup_entry
    for index, vehicle in enumerate(coordinator.data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2024-04-05 13:33:55.616 INFO (MainThread) [homeassistant.components.sensor] Setting up toyota.sensor
2024-04-05 13:33:55.616 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/sensor.py", line 209, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by mork993** [comment]
Same Issue. Same logs.
I am using new MyToyota app with Yaris Cross Hybrid.

**Comment by CM000n** [comment]
And another return value of the API that has changed here with `dcmSupplierName`. 🙄 
We cannot rely on anything with the Toyota API in its current state. This is really a pain in the arse. Sorry guys, I'll try to fix and adjust the models where I can. But it looks like there will be incompatibilities and errors with the Toyota API from time to time.

**Comment by manelmg** [comment]
Hi,
With the new integration version (), I get the same error: No devices or entities

**Comment by martinviktora** [comment]
I am facing the same issue with Lexus NX 2022 plug-in hybrid. I am ready to help with testing. I do not have any experience with Python (I know basic of PHP), I have experience with Postman - if needed.

**Comment by CM000n** [comment]
> I am facing the same issue with Lexus NX 2022 plug-in hybrid. I am ready to help with testing. I do not have any experience with Python (I know basic of PHP), I have experience with Postman - if needed.

Lexus IS currently not supported. You can support development in it here https://github.com/DurgNomis-drol/mytoyota/pull/316

**Comment by briandelicata** [comment]
@CM000n manifest.json should be updated to use mytoyota 2.1.2. It's working in HA for me.

**Comment by CM000n** [comment]
> @CM000n manifest.json should be updated to use mytoyota 2.1.2. It's working in HA for me.

🙄 😉 https://github.com/DurgNomis-drol/ha_toyota/pull/257

**Comment by TheNickFury** [comment]
Hi @CM000n ,
I installed the version of this issue but the problem persists. Logs:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/sensor.py", line 209, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/device_tracker.py", line 39, in async_setup_entry
    for index, vehicle in enumerate(coordinator.data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/binary_sensor.py", line 232, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable`

`4 validation errors for VehiclesResponseModel payload -> 0 -> dcm -> dcmDestination none is not an allowed value (type=type_error.none.not_allowed) payload -> 0 -> dcm -> dcmGrade none is not an allowed value (type=type_error.none.not_allowed) payload -> 0 -> dcm -> dcmSupplier none is not an allowed value (type=type_error.none.not_allowed) payload -> 0 -> dcm -> euiccid none is not an allowed value (type=type_error.none.not_allowed)`

**Comment by TheNickFury** [comment]
Hi guys news?

**Comment by CM000n** [comment]
Should be fixed by https://github.com/DurgNomis-drol/ha_toyota/pull/289
