### ISSUE TITLE
2024.4.4 error - unable to install package

### ISSUE THREAD

**Issue by fenty17** [DurgNomis-drol/ha_toyota#258]
**Describe the bug**

On updating to HA 2024.4.4, the integration fails to load. 

**To Reproduce**

Update and check logs

**Expected behavior**

Working integration 

**Logs**

```
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 20:51:14 (3 occurrences)
Last logged: 20:52:31

Unable to install package mytoyota==2.1.1: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [15 lines of output] running bdist_wheel running build running build_clib building 'libmarisa-trie' library creating build creating build/temp.linux-aarch64-cpython-312 creating build/temp.linux-aarch64-cpython-312/marisa-trie creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/io creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/trie creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/vector gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/agent.cc -o build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/agent.o error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for marisa-trie ERROR: Could not build wheels for marisa-trie, which is required to install pyproject.toml-based projects
```

**Comment by CM000n** [comment]
What installation method of Home Assistant are you using?

**Comment by renewoensdregt** [comment]
I have the same issue and use Home assistant Core 2024.4.4, supervisor 2024.04.0 on a dedicated RPI4

All latest versions.

**Comment by fenty17** [comment]
I'm also on RPi 4 running HAOS - core, supervisor etc all latest versions.

**Comment by LMT1337** [comment]
Same Problem, Running on rpi5 latest Update

**Comment by oskarhood** [comment]
Same here, rpi3

**Comment by darth-aragoth** [comment]
Same here after updating th to 2024.4.4

**Comment by designerferro** [comment]
> What installation method of Home Assistant are you using?

I have the same problem. I'm using HASSOSS:

- Core 2024.4.4
- Supervisor 2024.04.0
- Operating System 12.2
- Frontend 20240404.2

**Comment by chtichi** [comment]
Same here with Freebox delta Virtual Machine on core 2024.4.4

**Comment by Viqus** [comment]
Same here, I have not installed this integration previously.

My environment:
```
Core 2024.4.4
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2
HW ODROID-N2
```

I was able to "install" the repo through HACS with no problems, but when adding the integration through devices settings menu, after some loading I get the following error:

> Error
> Config flow could not be loaded: Unknown error

**Comment by durix75** [comment]
Same here. 
hope update will fix it soon. 
thanks

**Comment by bonepl** [comment]
Same here

**Comment by andyz68** [comment]
Same for me

**Comment by chrisvanberg** [comment]
> I have the same issue and use Home assistant Core 2024.4.4, supervisor 2024.04.0 on a dedicated RPI4
> 
> All latest versions.

Same as me !

HA picked those errors :
```
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: April 26, 2024 at 17:22:53 (3 occurrences)
Last logged: April 26, 2024 at 17:23:36

Unable to install package mytoyota==2.1.1: 
error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ 
exit code: 1 ╰─> [15 lines of output] running bdist_wheel running build running build_clib building 'libmarisa-trie' library creating build creating build/temp.linux-aarch64-cpython-312 creating build/temp.linux-aarch64-cpython-312/marisa-trie creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/io creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/trie creating build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/vector gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/agent.cc -o build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/agent.o error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for marisa-trie ERROR: Could not build wheels for marisa-trie, which is required to install pyproject.toml-based projects
```

```
Logger: homeassistant.setup
Source: setup.py:273
First occurred: April 26, 2024 at 17:23:36 (1 occurrences)
Last logged: April 26, 2024 at 17:23:36

Setup failed for custom integration 'toyota': Requirements for toyota not found: ['mytoyota==2.1.1'].
```

**Comment by vermut** [comment]
My wild guess that something on aarch64 platform is pulling in marisa-trie dep of older version, not Python 3.12 compatible. Need to find that dep and upgrade

https://github.com/pytries/marisa-trie/issues/93

**Comment by lukmus1** [comment]
Nie działa po aktualizacji ...

**Comment by VivantSenior** [comment]
I'm having the same issue after HA update to 2024.5.0:

rejestrator:%20homeassistant.util.package%0A%C5%B9r%C3%B3d%C5%82o%3A%20util/package.py:123%0APierwsze%20zdarzenie:%2022:12:44%20(3%20zdarzenia)%0AOstatnio%20zalogowany:%2022:13:32%0A%0AUnable%20to%20install%20package%20mytoyota==2.1.1:%20error:%20subprocess-exited-with-error%20%C3%97%20python%20setup.py%20bdist_wheel%20did%20not%20run%20successfully.%20%E2%94%82%20exit%20code:%201%20%E2%95%B0%E2%94%80%3E%20%5B15%20lines%20of%20output%5D%20running%20bdist_wheel%20running%20build%20running%20build_clib%20building%20'libmarisa-trie'%20library%20creating%20build%20creating%20build/temp.linux-aarch64-cpython-312%20creating%20build/temp.linux-aarch64-cpython-312/marisa-trie%20creating%20build/temp.linux-aarch64-cpython-312/marisa-trie/lib%20creating%20build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa%20creating%20build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire%20creating%20build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/io%20creating%20build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/trie%20creating%20build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/grimoire/vector%20gcc%20-fno-strict-overflow%20-Wsign-compare%20-DNDEBUG%20-g%20-O3%20-Wall%20-fno-semantic-interposition%20-fno-builtin-malloc%20-fno-builtin-calloc%20-fno-builtin-realloc%20-fno-builtin-free%20-DTHREAD_STACK_SIZE=0x100000%20-fPIC%20-Imarisa-trie/lib%20-Imarisa-trie/include%20-c%20marisa-trie/lib/marisa/agent.cc%20-o%20build/temp.linux-aarch64-cpython-312/marisa-trie/lib/marisa/agent.o%20error:%20command%20'gcc'%20failed:%20No%20such%20file%20or%20directory%20%5Bend%20of%20output%5D%20note:%20This%20error%20originates%20from%20a%20subprocess,%20and%20is%20likely%20not%20a%20problem%20with%20pip.%20ERROR:%20Failed%20building%20wheel%20for%20marisa-trie%20ERROR:%20Could%20not%20build%20wheels%20for%20marisa-trie,%20which%20is%20required%20to%20install%20pyproject.toml-based%20projects

**Comment by justinh998** [comment]
same for me

**Comment by AUSF** [comment]
Confirmed: it works again now! Thank you very much vermut!

**Comment by justinh998** [comment]
> Together with marisa-trie team we released a 3.12 wheel: https://github.com/pytries/marisa-trie/pull/101
> I *think* it should just start working now out of the box.

Small question, I had already manually installed the marisa_trie-1.1.0-cp312-cp312-musllinux_1_1_aarch64.whl in my home assitent supervisor. Do I have to uninstall it now to get the official version and get updates for it automatically?

**Comment by TorstenHamper** [comment]
> Together with marisa-trie team we released a 3.12 wheel: [pytries/marisa-trie#101](https://github.com/pytries/marisa-trie/pull/101) I _think_ it should just start working now out of the box.

Works like a charm! Many thanks!

**Comment by vermut** [comment]
> Small question, I had already manually installed the marisa_trie-1.1.0-cp312-cp312-musllinux_1_1_aarch64.whl in my home assitent supervisor. Do I have to uninstall it now to get the official version and get updates for it automatically? Thank your very much for that solution .

I think it will get auto-replaced by version 1.1.1, you don't need to do anything. If you want to be super-sure - remove it and run `pip3 install mytoyota==2.1.1` again. I think it will fetch fresh version.

**Comment by vermut** [comment]
@BoboTiG can you? ^^

**Comment by fenty17** [comment]
@vermut - confimed working for me after a restart - Pi4 running HAOS. Many thanks for the fix 👍🏼

**Comment by darth-aragoth** [comment]
> @vermut - confimed working for me after a restart - Pi4 running HAOS. Many thanks for the fix 👍🏼

32-bit or 64-bit system?

**Comment by vermut** [comment]
64-bit only. For 32-bit you'll have to follow https://github.com/pytries/marisa-trie/pull/102. Looks grim atm.

**Comment by fenty17** [comment]
> 32-bit or 64-bit system?

64

**Comment by frenck** [comment]
Thanks for the PR @vermut

Wheels are published, see: <https://wheels.home-assistant.io/musllinux-index/marisa-trie/>

The problem should be resolved immediately now.

**Comment by chtichi** [comment]
All datas are back on my home assistant. Thank you !

**Comment by amastrogiacomo1968** [comment]
> Thanks for the PR @vermut
> 
> Wheels are published, see: https://wheels.home-assistant.io/musllinux-index/marisa-trie/
> 
> The problem should be resolved immediately now.

How do you use these Wheels?
Sorry for my ignorance but this is all new. Thank you

**Comment by vermut** [comment]
> How do you use these Wheels? Sorry for my ignorance but this is all new. Thank you

Magic. Just restart HASS and it will work.

**Comment by CM000n** [comment]
Thank you all, and especially @vermut, for reporting, researching and fixing this issue!

**Comment by amastrogiacomo1968** [comment]
I confirm, after 3 restarts the function. Thank you
