### ISSUE TITLE
Integration unable to setup after updating to HA version 2024.5.0

### ISSUE THREAD

**Issue by sldewit** [DurgNomis-drol/ha_toyota#260]
After updating to Home assistant version 2024.5.0 the integration is unable to setup. See below error messages:
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/54032526/59b71b42-7e8a-4708-a0bb-41207c71466f)
[Error Toyota integration.log](https://github.com/DurgNomis-drol/ha_toyota/files/15185783/Error.Toyota.integration.log)

**Comment by FS1961** [comment]
Roger that, me too.  Can't remove or reinstall.

**Comment by joost11111** [comment]
> Roger that, me too. Can't remove or reinstall.

After the problem with the update to 2024.5.0 I downgraded to the Home Assistant 2024.4.4 but it is still not working?

**Comment by FS1961** [comment]
Same. Tried to restore an old backup as well. Can remove it either.

**Comment by gertlind** [comment]
Same here

**Comment by darth-aragoth** [comment]
> > Roger that, me too. Can't remove or reinstall.
> 
> After the problem with the update to 2024.5.0 I downgraded to the Home Assistant 2024.4.4 but it is still not working?

You have to downgrade to earlier version, integration stopped working with v2024.4.4.

**Comment by joost11111** [comment]
> > > Roger that, me too. Can't remove or reinstall.
> > 
> > 
> > After the problem with the update to 2024.5.0 I downgraded to the Home Assistant 2024.4.4 but it is still not working?
> 
> You have to downgrade to earlier version, integration stopped working with v2024.4.4.

I am quite sure that is was still working with the the previous v2024.4.4 version? Maybe better wait for a solution?

**Comment by darth-aragoth** [comment]
I currently use v2024.4.4 and integration is not loading.

```
Rejestrator: homeassistant.setup
Źródło: setup.py:273
Pierwsze zdarzenie: 03:26:06 (1 zdarzenia)
Ostatnio zalogowany: 03:26:06

Setup failed for custom integration 'toyota': Requirements for toyota not found: ['mytoyota==2.1.1'].
```

**Comment by joost11111** [comment]
> I currently use v2024.4.4 and integration is not loading.
> 
> ```
> Rejestrator: homeassistant.setup
> Źródło: setup.py:273
> Pierwsze zdarzenie: 03:26:06 (1 zdarzenia)
> Ostatnio zalogowany: 03:26:06
> 
> Setup failed for custom integration 'toyota': Requirements for toyota not found: ['mytoyota==2.1.1'].
> ```

I also downgraded to v2024.4.4 but is not working but it used to work. Did you get it working with an older version?

**Comment by darth-aragoth** [comment]
I didn't try, I hope it will be fixed soon 🙂

**Comment by FS1961** [comment]
I was able to remove the integration. I'll just wait for the fix?

**Comment by florianfish** [comment]
same problem here too!

**Comment by williamwwlr** [comment]
Meme soucis ici

**Comment by zemnet** [comment]
same problem

**Comment by vermut** [comment]
Fixed in https://github.com/pytries/marisa-trie/pull/101. Should just work.

**Comment by joost11111** [comment]
> Fixed in [pytries/marisa-trie#101](https://github.com/pytries/marisa-trie/pull/101). Should just work.

Do I have to install something or wait for a new version of the Toyota package?

**Comment by vermut** [comment]
Restart Hass, I think that should be enough.

**Comment by joost11111** [comment]
> Restart Hass, I think that should be enough.

Thanks! It is working again.

**Comment by darth-aragoth** [comment]
In my case, restart did not help. Tried several times

```
Rejestrator: homeassistant.util.package
Źródło: util/package.py:123
Pierwsze zdarzenie: 17:07:52 (3 zdarzenia)
Ostatnio zalogowany: 17:08:38

Unable to install package mytoyota==2.1.1: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [15 lines of output] running bdist_wheel running build running build_clib building 'libmarisa-trie' library creating build creating build/temp.linux-armv7l-cpython-312 creating build/temp.linux-armv7l-cpython-312/marisa-trie creating build/temp.linux-armv7l-cpython-312/marisa-trie/lib creating build/temp.linux-armv7l-cpython-312/marisa-trie/lib/marisa creating build/temp.linux-armv7l-cpython-312/marisa-trie/lib/marisa/grimoire creating build/temp.linux-armv7l-cpython-312/marisa-trie/lib/marisa/grimoire/io creating build/temp.linux-armv7l-cpython-312/marisa-trie/lib/marisa/grimoire/trie creating build/temp.linux-armv7l-cpython-312/marisa-trie/lib/marisa/grimoire/vector gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/agent.cc -o build/temp.linux-armv7l-cpython-312/marisa-trie/lib/marisa/agent.o error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for marisa-trie ERROR: Could not build wheels for marisa-trie, which is required to install pyproject.toml-based projects

```

**Comment by vermut** [comment]
It was only solved for aarch64. armv7l was already mentioned but seems like builder is unaware of that arch. And I don't have a device to test. Is it the same as armv7?

https://github.com/pytries/marisa-trie/pull/102

**Comment by darth-aragoth** [comment]
I don't know, I'm using Raspberry Pi 4, 32-bit OS

**Comment by FS1961** [comment]
I can confirm it’s working again. 
Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

**Comment by darth-aragoth** [comment]
After switching to 64bit system it's working again :) Thank you.

**Comment by amastrogiacomo1968** [comment]
> After switching to 64bit system it's working again :) Thank you.

What is the procedure for switching from the 32-bit version to the 64-bit version? Thank you

**Comment by williamwwlr** [comment]
C'est OK pour moi aussi

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vermut** [comment]
I only fixed installation issues, the `marisa-trie` bug. Toyota services being unavailable is beyond my control.

**Comment by sldewit** [comment]
After a reboot of HA it is working again for me. So I will close off this ticket.

**Comment by simaoguimaraes** [comment]
After uninstalling I'm unable to install Toyota Connected Services in HA. I get the following Error:

> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble
