### ISSUE TITLE
After upgrade to 2.0.4, there are no devices not entities loaded

### ISSUE THREAD

**Issue by Petucky** [DurgNomis-drol/ha_toyota#290]
After upgrade to 2.0.4, there are no devices not entities loaded.
I've seen a vehicle with 2.0.3 before it stopped working (as documented in https://github.com/DurgNomis-drol/ha_toyota/issues/286).

**Comment by ArnstadFredrik** [comment]
Similar but not the same issue. I updated and the vehicle appears, odometer, location and lock status. But the EV battery percentage dissapeared.

**Comment by hoffeck** [comment]
After the update, the fuel content of my corolla no longer shows up

**Comment by hugosanchezmartinez** [comment]
after update, working as expected. No issues so far

**Comment by TheNickFury** [comment]
Hi guys, I installed the version of this issue but the problem persists (same issue https://github.com/DurgNomis-drol/ha_toyota/issues/248). Logs:
2024-08-14 16:32:43.316 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota platform for sensor
Traceback (most recent call last):
  File "/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/sensor.py", line 209, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

But another log:
2024-08-14 16:26:18.907 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up tractive platform for device_tracker
Traceback (most recent call last):
  File "/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/homeassistant/components/tractive/device_tracker.py", line 30, in async_setup_entry
    entities = [TractiveDeviceTracker(client, item) for item in trackables]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/components/tractive/device_tracker.py", line 49, in __init__
    self._battery_level: int | None = item.hw_info.get("battery_level")
                                      ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by CM000n** [comment]
Sorry to disappoint you all

We should probably throw out all model assumptions for the Toyota API responses in the `mytoyota` lib and assume that no more values will be supplied at any time for parameter.

The Toyota API is simply bullshit in its structure and is changed with such frequency that our model assumptions are constantly breaking (as there is no official documentation of the API either).
In addition, the owner of the `mytoyota` and `ha_toyota` projects is unfortunately only sporadically available (I really hope he's okay ❤️) and this further delays adjustments and fixes.

As a result, I, for example, have put very little energy into the `mytoyota` lib and `ha_toyota` Home Assistant integration.

**Comment by Zegafur** [comment]
This workaround still works to get the fuel level showing again: https://github.com/DurgNomis-drol/ha_toyota/issues/273#issuecomment-2208407726

Line 242 in /homeassistant/custom_components/toyota/sensor.py can also be changed from 'PERCENTAGE' to 'None' to get the "battery level" to work.

You however have to add the percentage (%) symbol in the editor for the card to display that after the value. Perhaps there is a easy way to fix this if you know python.

**Comment by nisu66** [comment]
> This workaround still works to get the fuel level showing again: [#273 (comment)](https://github.com/DurgNomis-drol/ha_toyota/issues/273#issuecomment-2208407726)
> 
> Line 242 in /homeassistant/custom_components/toyota/sensor.py can also be changed from 'PERCENTAGE' to 'None' to get the "battery level" to work.
> 
> You however have to add the percentage (%) symbol in the editor for the card to display that after the value. Perhaps there is a easy way to fix this if you know python.
Perfect. It works. I used the usual system for both battery and fuel levels. Thanks

**Comment by elmaswebon** [comment]
> This workaround still works to get the fuel level showing again: [#273 (comment)](https://github.com/DurgNomis-drol/ha_toyota/issues/273#issuecomment-2208407726)
> 
> Line 242 in /homeassistant/custom_components/toyota/sensor.py can also be changed from 'PERCENTAGE' to 'None' to get the "battery level" to work.
> 
> You however have to add the percentage (%) symbol in the editor for the card to display that after the value. Perhaps there is a easy way to fix this if you know python.

After doing this, there´s an easy way to add the "%" only editing the configuration.yaml file and restarting HA:
https://github.com/DurgNomis-drol/ha_toyota/issues/273#issuecomment-2290811788

**Comment by ajain-93** [comment]
@Petucky Can you check if this works in 2.0.5?

**Comment by Petucky** [comment]
No,

even in 2.0.5, I receive following errors in log:

2 validation errors for NotificationResponseModel payload -> 0 -> notifications -> 15 -> vin none is not an allowed value (type=type_error.none.not_allowed) payload -> 0 -> notifications -> 16 -> vin none is not an allowed value (type=type_error.none.not_allowed)


Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/binary_sensor.py", line 232, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable


raceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/device_tracker.py", line 39, in async_setup_entry
    for index, vehicle in enumerate(coordinator.data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable


Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/sensor.py", line 209, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable



________________________________

**Comment by ajain-93** [comment]
Can you check in the app what notifications you have?

**Comment by Petucky** [comment]
Should I check anything specific?

The last one I have is 3 days old "The vehicle is now locked". Otherwise, the app works as expected.

**Comment by ajain-93** [comment]
What about the older ones, say postion 15-16 or so (i.e. 4-5 from bottom)?

**Comment by Petucky** [comment]
I have 37 notifications, from beginning (a new car).

But it's true I have specific notification due to tow installation:
15:  Please check the Tojota rear seat.  13 Aug 2024, 11:34
16:  O A malfunction in the Sonar System has  been detected. Immediately contact any  retailer to have your vehicle inspected!  13 Aug 2024, 11:03
17:  O A malfunction in the Electronically  Controlled Brake System has been  detected. Immediately contact any retailer  to have your vehicle inspected!  13 Aug 2024, 11:03
18:  Toyota boot/ hatch is open.  13 Aug 2024, 09:27
19:  Tojota has multiple vehicle alerts, please  check app for more details.  13 Aug 2024, 08:51


________________________________

**Comment by Petucky** [comment]
Update: Some new notifications came in and the device/entities are loaded correctly now.
