### ISSUE TITLE
Detected blocking call to open with args ('/root/.cache/toyota_credentials_cache_contains_secrets', 'w') inside the event loop

### ISSUE THREAD

**Issue by Szeryff** [DurgNomis-drol/ha_toyota#295]
**Describe the bug**
I have the following warning in log file:
> Detected blocking call to open with args ('/root/.cache/toyota_credentials_cache_contains_secrets', 'w') inside the event loop by custom integration 'toyota' at custom_components/toyota/__init__.py, line 66: await client.login() (offender: /usr/local/lib/python3.12/site-packages/mytoyota/controller.py, line 203: with open(str(CACHE_FILENAME), "w", encoding="utf-8") as f:), please create a bug report at https://github.com/DurgNomis-drol/ha_toyota/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/toyota/__init__.py", line 66, in async_setup_entry await client.login() 

**To Reproduce**
Appears while loading integration in HA. Same warning for 2.0.4 and 2.0.5. HA version 2024.8.2.

**Comment by willidh1** [comment]
I have a similar issue:

```
> -------------------------------------------------------------------
> Toyota Connected Services
> This is a custom integration!
> If you have any issues with this you need to open an issue here:
> https://github.com/DurgNomis-drol/ha_toyota/issues
> -------------------------------------------------------------------
> 
> 2024-08-27 01:06:06.246 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/root/.cache/toyota_credentials_cache_contains_secrets', 'w') inside the event loop by custom integration 'toyota' at custom_components/toyota/__init__.py, line 66: await client.login() (offender: /usr/local/lib/python3.12/site-packages/mytoyota/controller.py, line 203: with open(str(CACHE_FILENAME), "w", encoding="utf-8") as f:), please create a bug report at https://github.com/DurgNomis-drol/ha_toyota/issues
> For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
>     sys.exit(main())
>   File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
>     exit_code = runner.run(runtime_conf)
>   File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
>     return loop.run_until_complete(setup_and_run_hass(runtime_config))
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
>     self.run_forever()
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
>     self._run_once()
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
>     handle._run()
>   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
>     self._context.run(self._callback, *self._args)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
>     await self.async_setup(hass, integration=integration)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/toyota/__init__.py", line 66, in async_setup_entry
>     await client.login()
```

**Comment by CM000n** [comment]
Duplicate. See: https://github.com/DurgNomis-drol/ha_toyota/issues/271
