### ISSUE TITLE
Auto-detect languagecode

### ISSUE THREAD

**Issue by DurgNomis-drol** [DurgNomis-drol/ha_toyota#7]
**Describe the solution you'd like**
Instead of manually inputting language code, we need a way to auto detect it. If possible.

**Comment by DurgNomis-drol** [comment]
Not relevant anymore as it is now set to `en-gb` per default. Changing it does not change anything

**Comment by saintfrater** [comment]
@DurgNomis-drol :

I've Home Assistant 2021.8.5 (core-2021.8.5)
