### ISSUE TITLE
fuel tank status - too many digits

### ISSUE THREAD

**Issue by homonto** [DurgNomis-drol/ha_toyota#90]
Hi there,

After last upgrade of the integration the fuel tank status is not rounded to 2 places - do you think this could be changed in the integration or I should use some templates in HA?
Please have a look and advice 

![Screenshot 2021-12-02 at 21 54 20](https://user-images.githubusercontent.com/46562447/144509765-0f29587b-df02-4f52-8ba6-80e5c85588cd.jpg)

Thank you

**Comment by DurgNomis-drol** [comment]
There have been some discussion in HA core about how to best handle rounding, but since this there solution haven't been implemented i will round it here to 1 decimal place. Not sure why it was not before 😊

**Comment by DurgNomis-drol** [comment]
Should now be fixed in the master branch, will include it in a release soon :smiley:

**Comment by homonto** [comment]
I updated to master and it is superb - thank you
