### ISSUE TITLE
Language Code is not valid

### ISSUE THREAD

**Issue by trytogetme85** [DurgNomis-drol/ha_toyota#94]
**Describe the bug**
Language Code not working anymore

**To Reproduce**

Re-Add the integration, sign up
I have to enter **de-de**. But it says
"Language code is not valid."
Even the "da-dk" language-code is not working

**Expected behavior**
works since last month

**Screenshots**
https://imgur.com/a/ZbnMNVj

**Additional context**

**Comment by DurgNomis-drol** [comment]
Please update to the latest version, this bug should have been fixed over a month ago 😊

**Comment by trytogetme85** [comment]
> Please update to the latest version, this bug should have been fixed over a month ago 😊

indeed. But why does HACS didnt show me, that there is an update available?

**Comment by DurgNomis-drol** [comment]
I have no idea, what version do you have installed? Latest version is 1.2.6

**Comment by trytogetme85** [comment]
Yes, now i updated by manualy re-adding this git

**Comment by DurgNomis-drol** [comment]
What version of home Assistant are you running?
